var standards = [
	"Abattoir Ghoul",
	"Abbey Griffin",
	"Abrupt Decay",
	"Abundant Growth",
	"Acidic Slime",
	"Aerial Predation",
	"Aggravate",
	"Ajani's Sunstriker",
	"Ajani, Caller of the Pride",
	"Akroma's Memorial",
	"Alchemist's Apprentice",
	"Alchemist's Refuge",
	"Alpha Brawl",
	"Altar of the Lost",
	"Altar's Reap",
	"Amass the Components",
	"Ambush Viper",
	"Ancient Grudge",
	"Angel of Flight Alabaster",
	"Angel of Glory's Rise",
	"Angel of Jubilation",
	"Angel of Serenity",
	"Angel's Mercy",
	"Angel's Tomb",
	"Angelic Armaments",
	"Angelic Benediction",
	"Angelic Overseer",
	"Angelic Wall",
	"Annihilating Fire",
	"Appetite for Brains",
	"Aquus Steed",
	"Arbor Elf",
	"Arcane Melee",
	"Archaeomancer",
	"Archangel",
	"Archangel's Light",
	"Ravenous Demon",
	"Archdemon of Greed",
	"Archon of the Triumvirate",
	"Archweaver",
	"Archwing Dragon",
	"Arctic Aven",
	"Armada Wurm",
	"Armored Skaab",
	"Armory Guard",
	"Arms Dealer",
	"Army of the Damned",
	"Arrest",
	"Artful Dodge",
	"Ash Zealot",
	"Ashmouth Hound",
	"Assassin's Strike",
	"Attended Knight",
	"Auger Spree",
	"Augur of Bolas",
	"Avacyn's Collar",
	"Avacyn's Pilgrim",
	"Avacyn, Angel of Hope",
	"Avacynian Priest",
	"Aven Squire",
	"Avenging Arrow",
	"Axebane Guardian",
	"Axebane Stag",
	"Azor's Elocutors",
	"Azorius Arrester",
	"Azorius Charm",
	"Azorius Guildgate",
	"Azorius Justiciar",
	"Azorius Keyrune",
	"Back from the Brink",
	"Balefire Dragon",
	"Hanweir Watchkeep",
	"Bane of Hanweir",
	"Banishing Stroke",
	"Banners Raised",
	"Bar the Door",
	"Barter in Blood",
	"Batterhorn",
	"Battle Hymn",
	"Battle of Wits",
	"Battleflight Eagle",
	"Battleground Geist",
	"Bazaar Krovod",
	"Beguiler of Wills",
	"Bellows Lizard",
	"Bitterheart Witch",
	"Black Cat",
	"Bladed Bracers",
	"Bladetusk Boar",
	"Blasphemous Act",
	"Blazing Torch",
	"Blessings of Nature",
	"Blistercoil Weird",
	"Blood Artist",
	"Blood Crypt",
	"Blood Feud",
	"Blood Reckoning",
	"Bloodcrazed Neonate",
	"Bloodflow Connoisseur",
	"Bloodfray Giant",
	"Bloodgift Demon",
	"Bloodhunter Bat",
	"Bloodline Keeper",
	"Lord of Lineage",
	"Bloodthrone Vampire",
	"Blustersquall",
	"Bond Beetle",
	"Bonds of Faith",
	"Bone Splinters",
	"Bone to Ash",
	"Boneyard Wurm",
	"Bonfire of the Damned",
	"Borderland Ranger",
	"Boundless Realms",
	"Bountiful Harvest",
	"Bower Passage",
	"Brain Weevil",
	"Bramblecrush",
	"Break of Day",
	"Briarpack Alpha",
	"Brimstone Volley",
	"Bruna, Light of Alabaster",
	"Brushstrider",
	"Builder's Blessing",
	"Bump in the Night",
	"Burden of Guilt",
	"Burn at the Stake",
	"Burning Oil",
	"Burning Vengeance",
	"Butcher Ghoul",
	"Butcher's Cleaver",
	"Cackling Counterpart",
	"Call of the Conclave",
	"Call to Serve",
	"Call to the Kindred",
	"Cancel",
	"Canyon Minotaur",
	"Captain of the Mists",
	"Captain of the Watch",
	"Captain's Call",
	"Caravan Vigil",
	"Carnival Hellsteed",
	"Catacomb Slug",
	"Cathars' Crusade",
	"Cathedral of War",
	"Cathedral Sanctifier",
	"Cavern of Souls",
	"Cellar Door",
	"Centaur Courser",
	"Centaur Healer",
	"Centaur's Herald",
	"Chalice of Life",
	"Chalice of Death",
	"Champion of Lambholt",
	"Champion of the Parish",
	"Chandra's Fury",
	"Chandra, the Firebrand",
	"Chant of the Skifsang",
	"Chaos Imps",
	"Chapel Geist",
	"Charmbreaker Devils",
	"Chemister's Trick",
	"Chill of Foreboding",
	"Chorus of Might",
	"Chosen of Markov",
	"Markov's Servant",
	"Chromatic Lantern",
	"Chronic Flooding",
	"Chronomaton",
	"Civic Saber",
	"Civilized Scholar",
	"Homicidal Brute",
	"Claustrophobia",
	"Cleaver Riot",
	"Clifftop Retreat",
	"Clinging Mists",
	"Clock of Omens",
	"Cloistered Youth",
	"Unholy Fiend",
	"Clone",
	"Cloudshift",
	"Cobblebrute",
	"Cobbled Wings",
	"Codex Shredder",
	"Collective Blessing",
	"Commander's Authority",
	"Common Bond",
	"Concordia Pegasus",
	"Conjured Currency",
	"Conjurer's Closet",
	"Corpse Lunge",
	"Corpse Traders",
	"Corpsejack Menace",
	"Counterflux",
	"Counterlash",
	"Coursers' Accord",
	"Courtly Provocateur",
	"Cower in Fear",
	"Craterhoof Behemoth",
	"Craterize",
	"Creeping Renaissance",
	"Creepy Doll",
	"Cremate",
	"Crimson Muckwader",
	"Crippling Blight",
	"Crippling Chill",
	"Crosstown Courier",
	"Crossway Vampire",
	"Crusader of Odric",
	"Crushing Vines",
	"Crypt Creeper",
	"Cryptborn Horror",
	"Curiosity",
	"Curse of Bloodletting",
	"Curse of Death's Hold",
	"Curse of Echoes",
	"Curse of Exhaustion",
	"Curse of Misfortunes",
	"Curse of Oblivion",
	"Curse of Stalked Prey",
	"Curse of the Bloody Tome",
	"Curse of the Nightly Hunt",
	"Curse of the Pierced Heart",
	"Curse of Thirst",
	"Cursebreak",
	"Cyclonic Rift",
	"Daggerdrome Imp",
	"Dangerous Wager",
	"Dark Favor",
	"Dark Impostor",
	"Dark Revenant",
	"Darkthicket Wolf",
	"Dawntreader Elk",
	"Daybreak Ranger",
	"Nightfall Predator",
	"Dead Reveler",
	"Dead Weight",
	"Deadbridge Goliath",
	"Deadeye Navigator",
	"Deadly Allure",
	"Deadly Recluse",
	"Dearly Departed",
	"Death Wind",
	"Death's Caress",
	"Death's Presence",
	"Deathrite Shaman",
	"Defang",
	"Defy Death",
	"Delver of Secrets",
	"Insectile Aberration",
	"Demolish",
	"Demonic Rising",
	"Demonic Taskmaster",
	"Demonlord of Ashmouth",
	"Demonmail Hauberk",
	"Deranged Assistant",
	"Deranged Outcast",
	"Descendants' Path",
	"Descent into Madness",
	"Desecration Demon",
	"Desolate Lighthouse",
	"Desperate Ravings",
	"Destroy the Evidence",
	"Detention Sphere",
	"Devastation Tide",
	"Deviant Glee",
	"Devil's Play",
	"Devout Chaplain",
	"Diabolic Revelation",
	"Diregraf Captain",
	"Diregraf Escort",
	"Diregraf Ghoul",
	"Disciple of Bolas",
	"Disciple of Griselbrand",
	"Disentomb",
	"Dispel",
	"Dissipate",
	"Divination",
	"Divine Deflection",
	"Divine Favor",
	"Divine Reckoning",
	"Divine Verdict",
	"Doomed Traveler",
	"Door to Nothingness",
	"Doorkeeper",
	"Downpour",
	"Downsize",
	"Dragon Hatchling",
	"Dragonskull Summit",
	"Drainpipe Vermin",
	"Dramatic Rescue",
	"Dread Slaver",
	"Dreadbore",
	"Dreadwaters",
	"Dream Twist",
	"Dreg Mangler",
	"Driver of the Dead",
	"Drogskol Captain",
	"Drogskol Reaver",
	"Drowned Catacomb",
	"Drudge Beetle",
	"Druid's Deliverance",
	"Druid's Familiar",
	"Druids' Repository",
	"Dryad Militant",
	"Dual Casting",
	"Dungeon Geists",
	"Duress",
	"Duskdale Wurm",
	"Duskmantle Prowler",
	"Duty-Bound Dead",
	"Dynacharge",
	"Eaten by Spiders",
	"Elbrus, the Binding Blade",
	"Withengar Unbound",
	"Elder Cathar",
	"Elder of Laurels",
	"Elderscale Wurm",
	"Electrickery",
	"Elgaud Inquisitor",
	"Elgaud Shieldmate",
	"Elite Inquisitor",
	"Elixir of Immortality",
	"Elvish Archdruid",
	"Elvish Visionary",
	"Emancipation Angel",
	"Encrust",
	"Endless Ranks of the Dead",
	"Entreat the Angels",
	"Epic Experiment",
	"Erase",
	"Erdwal Ripper",
	"Essence Backlash",
	"Essence Drain",
	"Essence Harvest",
	"Essence of the Wild",
	"Essence Scatter",
	"Ethereal Armor",
	"Evernight Shade",
	"Evil Twin",
	"Evolving Wilds",
	"Executioner's Hood",
	"Explosive Impact",
	"Exquisite Blood",
	"Eyes in the Skies",
	"Faerie Impostor",
	"Faerie Invaders",
	"Faith's Reward",
	"Faith's Shield",
	"Faithless Looting",
	"Falkenrath Aristocrat",
	"Falkenrath Exterminator",
	"Falkenrath Marauders",
	"Falkenrath Noble",
	"Falkenrath Torturer",
	"Fall of the Gavel",
	"Farbog Boneflinger",
	"Farbog Explorer",
	"Farseek",
	"Favor of the Woods",
	"Favorable Winds",
	"Feed the Pack",
	"Feeling of Dread",
	"Fencing Ace",
	"Feral Ridgewolf",
	"Fervent Cathar",
	"Fervor",
	"Festerhide Boar",
	"Fettergeist",
	"Fiend Hunter",
	"Fiend of the Shadows",
	"Fire Elemental",
	"Firemind's Foresight",
	"Fires of Undeath",
	"Firewing Phoenix",
	"Flames of the Firebrand",
	"Flayer of the Hatebound",
	"Fleeting Distraction",
	"Fling",
	"Flinthoof Boar",
	"Flowering Lumberknot",
	"Fog",
	"Fog Bank",
	"Forbidden Alchemy",
	"Forest",
	"Forge Devil",
	"Fortress Crab",
	"Frightful Delusion",
	"Frostburn Weird",
	"Full Moon's Rise",
	"Fungal Sprouting",
	"Furnace Whelp",
	"Furor of the Bitten",
	"Gallows at Willow Hill",
	"Gallows Warden",
	"Galvanic Alchemist",
	"Galvanic Juggernaut",
	"Gang of Devils",
	"Garruk Relentless",
	"Garruk, the Veil-Cursed",
	"Garruk's Packleader",
	"Garruk, Primal Hunter",
	"Gatecreeper Vine",
	"Gather the Townsfolk",
	"Gatstaf Shepherd",
	"Gatstaf Howler",
	"Gavony Ironwright",
	"Gavony Township",
	"Geist of Saint Traft",
	"Geist Snatch",
	"Geist Trappers",
	"Geist-Honored Monk",
	"Geistcatcher's Rig",
	"Geistflame",
	"Gem of Becoming",
	"Geralf's Messenger",
	"Geralf's Mindcrusher",
	"Soul Seizer",
	"Ghastly Haunting",
	"Ghost Quarter",
	"Ghostform",
	"Ghostly Flicker",
	"Ghostly Possession",
	"Ghostly Touch",
	"Ghoulcaller's Bell",
	"Ghoulcaller's Chant",
	"Ghoulflesh",
	"Ghoulraiser",
	"Ghoultree",
	"Giant Growth",
	"Giant Scorpion",
	"Gilded Lotus",
	"Gisela, Blade of Goldnight",
	"Glacial Fortress",
	"Gloom Surgeon",
	"Gloomwidow",
	"Glorious Charge",
	"Gnaw to the Bone",
	"Gobbling Ooze",
	"Goblin Arsonist",
	"Goblin Battle Jester",
	"Goblin Electromancer",
	"Goblin Rally",
	"Goldnight Commander",
	"Goldnight Redeemer",
	"Golgari Charm",
	"Golgari Decoy",
	"Golgari Guildgate",
	"Golgari Keyrune",
	"Golgari Longlegs",
	"Gore-House Chainwalker",
	"Grafdigger's Cage",
	"Grasp of Phantoms",
	"Grave Betrayal",
	"Grave Bramble",
	"Grave Exchange",
	"Gravecrawler",
	"Gravepurge",
	"Gravetiller Wurm",
	"Graveyard Shovel",
	"Griffin Protector",
	"Grim Backwoods",
	"Grim Flowering",
	"Grim Roustabout",
	"Grimgrin, Corpse-Born",
	"Grimoire of the Dead",
	"Griptide",
	"Griselbrand",
	"Grisly Salvage",
	"Grizzled Outcasts",
	"Krallenhorde Wantons",
	"Ground Seal",
	"Grounded",
	"Grove of the Guardian",
	"Growing Ranks",
	"Gruesome Deformity",
	"Gruesome Discovery",
	"Gryff Vanguard",
	"Guardian Lions",
	"Guardians of Akrasa",
	"Guild Feud",
	"Guise of Fire",
	"Gutter Grime",
	"Guttersnipe",
	"Hallowed Fountain",
	"Hamlet Captain",
	"Hamletback Goliath",
	"Hanweir Lancer",
	"Harbor Bandit",
	"Harbor Serpent",
	"Harrowing Journey",
	"Harvest Pyre",
	"Harvester of Souls",
	"Haunted Fengraf",
	"Haunted Guardian",
	"Havengul Lich",
	"Havengul Runebinder",
	"Havengul Skaab",
	"Havengul Vampire",
	"Havoc Festival",
	"Headless Skaab",
	"Healer of the Pride",
	"Heartless Summoning",
	"Heavy Mattock",
	"Heckling Fiends",
	"Heirs of Stromkirk",
	"Hellhole Flailer",
	"Hellion Crucible",
	"Hellrider",
	"Helvault",
	"Herald of War",
	"Heretic's Punishment",
	"Heroes' Reunion",
	"Highborn Ghoul",
	"Hinterland Harbor",
	"Hinterland Hermit",
	"Hinterland Scourge",
	"Hollowhenge Beast",
	"Hollowhenge Scavenger",
	"Hollowhenge Spirit",
	"Holy Justiciar",
	"Homicidal Seclusion",
	"Horncaller's Chant",
	"Hound of Griselbrand",
	"Hover Barrier",
	"Howlgeist",
	"Mayor of Avabruck",
	"Howlpack Alpha",
	"Villagers of Estwald",
	"Howlpack of Estwald",
	"Human Frailty",
	"Hunger of the Howlpack",
	"Hunted Ghoul",
	"Huntmaster of the Fells",
	"Ravager of the Fells",
	"Hussar Patrol",
	"Hydrosurge",
	"Hypersonic Dragon",
	"Hysterical Blindness",
	"Immerwolf",
	"Inaction Injunction",
	"Increasing Ambition",
	"Increasing Confusion",
	"Increasing Devotion",
	"Increasing Savagery",
	"Increasing Vengeance",
	"Index",
	"Infernal Plunge",
	"Infinite Reflection",
	"Inquisitor's Flail",
	"Inspiration",
	"Instigator Gang",
	"Wildblood Pack",
	"Intangible Virtue",
	"Into the Maw of Hell",
	"Into the Void",
	"Intrepid Hero",
	"Invisible Stalker",
	"Village Ironsmith",
	"Ironfang",
	"Island",
	"Isolated Chapel",
	"Isperia's Skywatch",
	"Isperia, Supreme Judge",
	"Izzet Charm",
	"Izzet Guildgate",
	"Izzet Keyrune",
	"Izzet Staticaster",
	"Jace's Phantasm",
	"Jace, Architect of Thought",
	"Jace, Memory Adept",
	"Jar of Eyeballs",
	"Jarad's Orders",
	"Jarad, Golgari Lich Lord",
	"Jayemdae Tome",
	"Joint Assault",
	"Judge's Familiar",
	"Keening Apparition",
	"Kessig Cagebreakers",
	"Kessig Malcontents",
	"Kessig Recluse",
	"Kessig Wolf",
	"Kessig Wolf Run",
	"Killing Wave",
	"Kindercatch",
	"Kindled Fury",
	"Kitesail",
	"Knight of Glory",
	"Knight of Infamy",
	"Knightly Valor",
	"Korozda Guildmage",
	"Korozda Monitor",
	"Kraken Hatchling",
	"Wolfbitten Captive",
	"Krallenhorde Killer",
	"Krenko's Command",
	"Krenko, Mob Boss",
	"Kruin Outlaw",
	"Terror of Kruin Pass",
	"Kruin Striker",
	"Laboratory Maniac",
	"Lair Delve",
	"Lambholt Elder",
	"Silverpelt Werewolf",
	"Lantern Spirit",
	"Latch Seeker",
	"Launch Party",
	"Leap of Faith",
	"Lightning Mauler",
	"Lightning Prowess",
	"Liliana of the Dark Realms",
	"Liliana of the Veil",
	"Liliana's Shade",
	"Lingering Souls",
	"Lobber Crew",
	"Lone Revenant",
	"Lost in the Mist",
	"Lost in the Woods",
	"Lotleth Troll",
	"Loxodon Smiter",
	"Loyal Cathar",
	"Unhallowed Cathar",
	"Ludevic's Test Subject",
	"Ludevic's Abomination",
	"Lumberknot",
	"Lunar Mystic",
	"Lyev Skyknight",
	"Maalfeld Twins",
	"Mad Prophet",
	"Magmaquake",
	"Make a Wish",
	"Makeshift Mauler",
	"Malicious Intent",
	"Malignus",
	"Mana Bloom",
	"Manor Gargoyle",
	"Manor Skeleton",
	"Mark of Mutiny",
	"Mark of the Vampire",
	"Markov Blademaster",
	"Markov Patrician",
	"Markov Warlord",
	"Marrow Bats",
	"Martial Law",
	"Mask of Avacyn",
	"Mass Appeal",
	"Master of the Pearl Trident",
	"Mausoleum Guard",
	"Maw of the Mire",
	"Memory's Journey",
	"Mental Agony",
	"Mentor of the Meek",
	"Reckless Waif",
	"Merciless Predator",
	"Mercurial Chemister",
	"Merfolk of the Pearl Trident",
	"Midnight Duelist",
	"Midnight Guard",
	"Midnight Haunting",
	"Midvast Protector",
	"Mikaeus, the Lunarch",
	"Mikaeus, the Unhallowed",
	"Mind Rot",
	"Mind Sculpt",
	"Mindclaw Shaman",
	"Mindshrieker",
	"Minotaur Aggressor",
	"Mirror-Mad Phantasm",
	"Mist Raven",
	"Misthollow Griffin",
	"Mizzium Mortars",
	"Mizzium Skin",
	"Moan of the Unhallowed",
	"Mogg Flunkies",
	"Moldgraf Monstrosity",
	"Moment of Heroism",
	"Mondronen Shaman",
	"Tovolar's Magehunter",
	"Moon Heron",
	"Moonlight Geist",
	"Moonmist",
	"Scorned Villager",
	"Moonscarred Werewolf",
	"Moonsilver Spear",
	"Moonveil Dragon",
	"Moorland Haunt",
	"Moorland Inquisitor",
	"Morkrut Banshee",
	"Mountain",
	"Mulch",
	"Murder",
	"Murder of Crows",
	"Mutilate",
	"Mwonvuli Beast Tracker",
	"Mystic Retrieval",
	"Narstad Scrapper",
	"Natural End",
	"Naturalize",
	"Nearheath Pilgrim",
	"Nearheath Stalker",
	"Necrobite",
	"Necropolis Regent",
	"Nefarox, Overlord of Grixis",
	"Negate",
	"Nephalia Drownyard",
	"Nephalia Seakite",
	"Nephalia Smuggler",
	"Nettle Swine",
	"Nevermore",
	"New Prahv Guildmage",
	"Niblis of the Breath",
	"Niblis of the Mist",
	"Niblis of the Urn",
	"Nicol Bolas, Planeswalker",
	"Night Revelers",
	"Night Terrors",
	"Nightbird's Clutches",
	"Nightshade Peddler",
	"Niv-Mizzet, Dracogenius",
	"Nivix Guildmage",
	"Nivmagus Elemental",
	"Oak Street Innkeeper",
	"Oblivion Ring",
	"Odric, Master Tactician",
	"Ogre Jailbreaker",
	"Olivia Voldaren",
	"Omniscience",
	"One-Eyed Scarecrow",
	"Orchard Spirit",
	"Otherworld Atlas",
	"Outwit",
	"Overgrown Tomb",
	"Pacifism",
	"Pack Rat",
	"Palisade Giant",
	"Parallel Lives",
	"Paralyzing Grasp",
	"Paraselene",
	"Past in Flames",
	"Pathbreaker Wurm",
	"Peel from Reality",
	"Perilous Shadow",
	"Phantom General",
	"Phylactery Lich",
	"Phyrexian Hulk",
	"Pillar of Flame",
	"Pillarfield Ox",
	"Pitchburn Devils",
	"Pithing Needle",
	"Plains",
	"Planar Cleansing",
	"Plummet",
	"Polluted Dead",
	"Precinct Captain",
	"Predator Ooze",
	"Predator's Gambit",
	"Predatory Rampage",
	"Prey Upon",
	"Primal Clay",
	"Primal Huntbeast",
	"Primal Surge",
	"Primordial Hydra",
	"Prized Elephant",
	"Psychic Spiral",
	"Public Execution",
	"Purify the Grave",
	"Pursuit of Flight",
	"Pyreheart Wolf",
	"Pyroconvergence",
	"Quirion Dryad",
	"Racecourse Fury",
	"Rage Thrower",
	"Raging Poltergeist",
	"Rain of Blades",
	"Rain of Thorns",
	"Rakdos Cackler",
	"Rakdos Charm",
	"Rakdos Guildgate",
	"Rakdos Keyrune",
	"Rakdos Ragemutt",
	"Rakdos Ringleader",
	"Rakdos Shred-Freak",
	"Rakdos's Return",
	"Rakdos, Lord of Riots",
	"Rakish Heir",
	"Rally the Peasants",
	"Tormented Pariah",
	"Rampaging Werewolf",
	"Rancor",
	"Ranger's Guile",
	"Ranger's Path",
	"Ravenous Rats",
	"Ray of Revelation",
	"Reap the Seagraf",
	"Reaper from the Abyss",
	"Rebuke",
	"Reckless Brute",
	"Redirect",
	"Reforge the Soul",
	"Relentless Skaabs",
	"Reliquary Tower",
	"Renegade Demon",
	"Requiem Angel",
	"Rest in Peace",
	"Restoration Angel",
	"Revenge of the Hunted",
	"Reverberate",
	"Revive",
	"Rewind",
	"Rhox Faithmender",
	"Riders of Gavony",
	"Righteous Authority",
	"Righteous Blow",
	"Ring of Evos Isle",
	"Ring of Kalonia",
	"Ring of Thune",
	"Ring of Valkas",
	"Ring of Xathrid",
	"Riot Devils",
	"Riot Ringleader",
	"Rise from the Grave",
	"Risen Sanctuary",
	"Rite of Ruin",
	"Rites of Reaping",
	"Rix Maadi Guildmage",
	"Roaring Primadox",
	"Rogue's Passage",
	"Rolling Temblor",
	"Rooftop Storm",
	"Rootborn Defenses",
	"Rootbound Crag",
	"Rotcrown Ghoul",
	"Rotting Fensnake",
	"Rubbleback Rhino",
	"Rummaging Goblin",
	"Runechanter's Pike",
	"Runewing",
	"Runic Repetition",
	"Rush of Blood",
	"Russet Wolves",
	"Safe Passage",
	"Sanctuary Cat",
	"Sands of Delirium",
	"Savage Surge",
	"Saving Grasp",
	"Scalding Devil",
	"Scorch the Fields",
	"Scourge of Geier Reach",
	"Scrapskin Drake",
	"Screeching Bat",
	"Stalking Vampire",
	"Screeching Skaab",
	"Scroll of Avacyn",
	"Scroll of Griselbrand",
	"Scroll Thief",
	"Seance",
	"Search the City",
	"Search Warrant",
	"Searchlight Geist",
	"Searing Spear",
	"Second Guess",
	"Secrets of the Dead",
	"Security Blockade",
	"Seek the Horizon",
	"Selesnya Charm",
	"Selesnya Guildgate",
	"Selesnya Keyrune",
	"Selesnya Sentry",
	"Selfless Cathar",
	"Selhoff Occultist",
	"Seller of Songbirds",
	"Sensory Deprivation",
	"Sentinel Spider",
	"Seraph of Dawn",
	"Seraph Sanctuary",
	"Serpent's Gift",
	"Serra Angel",
	"Serra Avatar",
	"Serra Avenger",
	"Servant of Nefarox",
	"Sever the Bloodline",
	"Sewer Shambler",
	"Sharpened Pitchfork",
	"Shattered Perception",
	"Sheltering Word",
	"Shimian Specter",
	"Shimmering Grotto",
	"Show of Valor",
	"Shriekgeist",
	"Shrieking Affliction",
	"Sigarda, Host of Herons",
	"Sightless Ghoul",
	"Sign in Blood",
	"Silent Departure",
	"Silklash Spider",
	"Silver-Inlaid Dagger",
	"Silverblade Paladin",
	"Silverchase Fox",
	"Silverclaw Griffin",
	"Silvercoat Lion",
	"Skaab Goliath",
	"Skaab Ruinator",
	"Skeletal Grimace",
	"Skillful Lunge",
	"Skirsdag Cultist",
	"Skirsdag Flayer",
	"Skirsdag High Priest",
	"Skull Rend",
	"Skyline Predator",
	"Skymark Roc",
	"Slaughter Games",
	"Slayer of the Wicked",
	"Slayers' Stronghold",
	"Sleep",
	"Slime Molding",
	"Slitherhead",
	"Sluiceway Scorpion",
	"Slum Reaper",
	"Slumbering Dragon",
	"Smelt",
	"Smite the Monstrous",
	"Snapcaster Mage",
	"Snare the Skies",
	"Somberwald Dryad",
	"Somberwald Sage",
	"Somberwald Spider",
	"Somberwald Vigilante",
	"Sorin, Lord of Innistrad",
	"Soul of the Harvest",
	"Soul Tithe",
	"Soulcage Fiend",
	"Soulsworn Spirit",
	"Spare from Evil",
	"Spawn of Rix Maadi",
	"Spectral Flight",
	"Spectral Gateguards",
	"Spectral Prison",
	"Spectral Rider",
	"Spelltwine",
	"Sphere of Safety",
	"Sphinx of the Chimes",
	"Sphinx of Uthuun",
	"Sphinx's Revelation",
	"Spider Spawning",
	"Spidery Grasp",
	"Spiked Baloth",
	"Spirit Away",
	"Spiteful Shadows",
	"Splatter Thug",
	"Splinterfright",
	"Stab Wound",
	"Staff of Nin",
	"Stealer of Secrets",
	"Steam Vents",
	"Stensia Bloodhall",
	"Stern Mentor",
	"Stitched Drake",
	"Stitcher's Apprentice",
	"Stolen Goods",
	"Stonefare Crocodile",
	"Stonewright",
	"Stony Silence",
	"Stormbound Geist",
	"Stormtide Leviathan",
	"Strangleroot Geist",
	"Street Spasm",
	"Street Sweeper",
	"Stromkirk Captain",
	"Stromkirk Noble",
	"Stromkirk Patrol",
	"Stuffy Doll",
	"Sturmgeist",
	"Sublime Archangel",
	"Sudden Disappearance",
	"Sulfur Falls",
	"Sundering Growth",
	"Sunpetal Grove",
	"Sunspire Griffin",
	"Supreme Verdict",
	"Survey the Wreckage",
	"Swamp",
	"Swift Justice",
	"Switcheroo",
	"Syncopate",
	"Tablet of the Guilds",
	"Talons of Falkenrath",
	"Talrand's Invocation",
	"Talrand, Sky Summoner",
	"Tamiyo, the Moon Sage",
	"Tandem Lookout",
	"Tavern Swindler",
	"Teleportal",
	"Temple Garden",
	"Temporal Mastery",
	"Tenement Crasher",
	"Terminus",
	"Terrifying Presence",
	"Terrus Wurm",
	"Thalia, Guardian of Thraben",
	"Thatcher Revolt",
	"Think Twice",
	"Thought Scour",
	"Thoughtflare",
	"Thraben Doomsayer",
	"Thraben Heretic",
	"Thraben Sentry",
	"Thraben Militia",
	"Thraben Purebloods",
	"Thraben Valiant",
	"Thragtusk",
	"Thrill-Kill Assassin",
	"Thunderbolt",
	"Thundermaw Hellkite",
	"Thunderous Wrath",
	"Tibalt, the Fiend-Blooded",
	"Timberland Guide",
	"Timberpack Wolf",
	"Titanic Growth",
	"Torch Fiend",
	"Tormented Soul",
	"Tormentor's Trident",
	"Tormod's Crypt",
	"Touch of the Eternal",
	"Tower Drake",
	"Tower Geist",
	"Towering Indrik",
	"Tracker's Instincts",
	"Trading Post",
	"Tragic Slip",
	"Trained Caracal",
	"Traitorous Blood",
	"Traitorous Instinct",
	"Transguild Promenade",
	"Travel Preparations",
	"Traveler's Amulet",
	"Treacherous Pit-Dweller",
	"Treasured Find",
	"Tree of Redemption",
	"Trepanation Blade",
	"Trestle Troll",
	"Tribute to Hunger",
	"Tricks of the Trade",
	"Triumph of Cruelty",
	"Triumph of Ferocity",
	"Trostani's Judgment",
	"Trostani, Selesnya's Voice",
	"Trumpet Blast",
	"Trusted Forcemage",
	"Turn to Slag",
	"Typhoid Rats",
	"Tyrant of Discord",
	"Ultimate Price",
	"Ulvenwald Bear",
	"Ulvenwald Mystics",
	"Ulvenwald Primordials",
	"Ulvenwald Tracker",
	"Unbreathing Horde",
	"Unburial Rites",
	"Uncanny Speed",
	"Undead Alchemist",
	"Undead Executioner",
	"Underworld Connections",
	"Undying Evil",
	"Unhallowed Pact",
	"Unruly Mob",
	"Unsummon",
	"Urban Burgeoning",
	"Urgent Exorcism",
	"Utvara Hellkite",
	"Vampire Interloper",
	"Vampire Nighthawk",
	"Vampire Nocturnus",
	"Vampiric Fury",
	"Vandalblast",
	"Vanguard's Shield",
	"Vanishment",
	"Vassal Soul",
	"Vastwood Gorger",
	"Vault of the Archangel",
	"Vedalken Entrancer",
	"Veilborn Ghoul",
	"Vengeful Vampire",
	"Vessel of Endless Rest",
	"Vexing Devil",
	"Viashino Racketeer",
	"Victim of Night",
	"Vigilante Justice",
	"Vile Rebirth",
	"Village Bell-Ringer",
	"Village Cannibals",
	"Village Survivors",
	"Vitu-Ghazi Guildmage",
	"Voice of the Provinces",
	"Voiceless Spirit",
	"Void Stalker",
	"Voidwielder",
	"Volatile Rig",
	"Volcanic Geyser",
	"Volcanic Strength",
	"Vorapede",
	"Vorstclaw",
	"Vraska the Unseen",
	"Wakedancer",
	"Walking Corpse",
	"Wall of Fire",
	"Wandering Wolf",
	"War Falcon",
	"War Priest of Thune",
	"Warclamp Mastiff",
	"Warden of the Wall",
	"Watercourser",
	"Wayfaring Temple",
	"Welkin Tern",
	"Afflicted Deserter",
	"Werewolf Ransacker",
	"Wild Beastmaster",
	"Wild Defiance",
	"Wild Guess",
	"Wild Hunger",
	"Wildwood Geist",
	"Wind Drake",
	"Wingcrafter",
	"Wit's End",
	"Witchbane Orb",
	"Wolfhunter's Quiver",
	"Wolfir Avenger",
	"Wolfir Silverheart",
	"Wooden Stake",
	"Woodland Cemetery",
	"Woodland Sleuth",
	"Worldfire",
	"Worldspine Wurm",
	"Wrack with Madness",
	"Wreath of Geists",
	"Xathrid Gorgon",
	"Yeva's Forcemage",
	"Yeva, Nature's Herald",
	"Yew Spirit",
	"Young Wolf",
	"Zanikev Locust",
	"Zealous Conscripts",
	"Zealous Strike",
	"Zombie Apocalypse",
	"Zombie Goliath"
];
