var standards = [
	"Abattoir Ghoul",
	"Abbey Griffin",
	"Abrupt Decay",
	"Abundant Growth",
	"Acidic Slime",
	"Act of Treason",
	"Adaptive Snapjaw",
	"Aerial Maneuver",
	"Aerial Predation",
	"AEtherize",
	"Aggravate",
	"Agoraphobia",
	"Ajani's Sunstriker",
	"Ajani, Caller of the Pride",
	"Akroma's Memorial",
	"Alchemist's Apprentice",
	"Alchemist's Refuge",
	"Alms Beast",
	"Alpha Authority",
	"Alpha Brawl",
	"Altar of the Lost",
	"Altar's Reap",
	"Amass the Components",
	"Ambush Viper",
	"Ancient Grudge",
	"Angel of Flight Alabaster",
	"Angel of Glory's Rise",
	"Angel of Jubilation",
	"Angel of Serenity",
	"Angel's Mercy",
	"Angel's Tomb",
	"Angelic Armaments",
	"Angelic Benediction",
	"Angelic Edict",
	"Angelic Overseer",
	"Angelic Skirmisher",
	"Angelic Wall",
	"Annihilating Fire",
	"Appetite for Brains",
	"Aquus Steed",
	"Arbor Elf",
	"Arcane Melee",
	"Archaeomancer",
	"Archangel",
	"Archangel's Light",
	"Ravenous Demon",
	"Archdemon of Greed",
	"Archon of the Triumvirate",
	"Archweaver",
	"Archwing Dragon",
	"Arctic Aven",
	"Armada Wurm",
	"Armored Skaab",
	"Armored Transport",
	"Armory Guard",
	"Arms Dealer",
	"Army of the Damned",
	"Arrest",
	"Arrows of Justice",
	"Artful Dodge",
	"Ash Zealot",
	"Ashmouth Hound",
	"Assassin's Strike",
	"Assault Griffin",
	"Assemble the Legion",
	"Attended Knight",
	"Auger Spree",
	"Augur of Bolas",
	"Aurelia's Fury",
	"Aurelia, the Warleader",
	"Avacyn's Collar",
	"Avacyn's Pilgrim",
	"Avacyn, Angel of Hope",
	"Avacynian Priest",
	"Aven Squire",
	"Avenging Arrow",
	"Axebane Guardian",
	"Axebane Stag",
	"Azor's Elocutors",
	"Azorius Arrester",
	"Azorius Charm",
	"Azorius Guildgate",
	"Azorius Justiciar",
	"Azorius Keyrune",
	"Back from the Brink",
	"Balefire Dragon",
	"Balustrade Spy",
	"Bane Alley Broker",
	"Hanweir Watchkeep",
	"Bane of Hanweir",
	"Banishing Stroke",
	"Banners Raised",
	"Bar the Door",
	"Barter in Blood",
	"Basilica Guards",
	"Basilica Screecher",
	"Batterhorn",
	"Battle Hymn",
	"Battle of Wits",
	"Battleflight Eagle",
	"Battleground Geist",
	"Bazaar Krovod",
	"Beckon Apparition",
	"Beguiler of Wills",
	"Bellows Lizard",
	"Biomass Mutation",
	"Bioshift",
	"Biovisionary",
	"Bitterheart Witch",
	"Black Cat",
	"Bladed Bracers",
	"Bladetusk Boar",
	"Blasphemous Act",
	"Blazing Torch",
	"Blessings of Nature",
	"Blind Obedience",
	"Blistercoil Weird",
	"Blood Artist",
	"Blood Crypt",
	"Blood Feud",
	"Blood Reckoning",
	"Bloodcrazed Neonate",
	"Bloodflow Connoisseur",
	"Bloodfray Giant",
	"Bloodgift Demon",
	"Bloodhunter Bat",
	"Bloodline Keeper",
	"Lord of Lineage",
	"Bloodthrone Vampire",
	"Blustersquall",
	"Bomber Corps",
	"Bond Beetle",
	"Bonds of Faith",
	"Bone Splinters",
	"Bone to Ash",
	"Boneyard Wurm",
	"Bonfire of the Damned",
	"Borborygmos Enraged",
	"Borderland Ranger",
	"Boros Charm",
	"Boros Elite",
	"Boros Guildgate",
	"Boros Keyrune",
	"Boros Reckoner",
	"Boundless Realms",
	"Bountiful Harvest",
	"Bower Passage",
	"Brain Weevil",
	"Bramblecrush",
	"Break of Day",
	"Breeding Pool",
	"Briarpack Alpha",
	"Brimstone Volley",
	"Bruna, Light of Alabaster",
	"Brushstrider",
	"Builder's Blessing",
	"Bump in the Night",
	"Burden of Guilt",
	"Burn at the Stake",
	"Burning Oil",
	"Burning Vengeance",
	"Burning-Tree Emissary",
	"Burst of Strength",
	"Butcher Ghoul",
	"Butcher's Cleaver",
	"Cackling Counterpart",
	"Call of the Conclave",
	"Call of the Nightwing",
	"Call to Serve",
	"Call to the Kindred",
	"Cancel",
	"Canyon Minotaur",
	"Captain of the Mists",
	"Captain of the Watch",
	"Captain's Call",
	"Caravan Vigil",
	"Carnival Hellsteed",
	"Cartel Aristocrat",
	"Catacomb Slug",
	"Cathars' Crusade",
	"Cathedral of War",
	"Cathedral Sanctifier",
	"Cavern of Souls",
	"Cellar Door",
	"Centaur Courser",
	"Centaur Healer",
	"Centaur's Herald",
	"Chalice of Life",
	"Chalice of Death",
	"Champion of Lambholt",
	"Champion of the Parish",
	"Chandra's Fury",
	"Chandra, the Firebrand",
	"Chant of the Skifsang",
	"Chaos Imps",
	"Chapel Geist",
	"Charmbreaker Devils",
	"Chemister's Trick",
	"Chill of Foreboding",
	"Chorus of Might",
	"Chosen of Markov",
	"Markov's Servant",
	"Chromatic Lantern",
	"Chronic Flooding",
	"Chronomaton",
	"Cinder Elemental",
	"Civic Saber",
	"Civilized Scholar",
	"Homicidal Brute",
	"Clan Defiance",
	"Claustrophobia",
	"Cleaver Riot",
	"Clifftop Retreat",
	"Clinging Anemones",
	"Clinging Mists",
	"Clock of Omens",
	"Cloistered Youth",
	"Unholy Fiend",
	"Clone",
	"Cloudfin Raptor",
	"Cloudshift",
	"Cobblebrute",
	"Cobbled Wings",
	"Codex Shredder",
	"Coerced Confession",
	"Collective Blessing",
	"Commander's Authority",
	"Common Bond",
	"Concordia Pegasus",
	"Conjured Currency",
	"Conjurer's Closet",
	"Consuming Aberration",
	"Contaminated Ground",
	"Corpse Blockade",
	"Corpse Lunge",
	"Corpse Traders",
	"Corpsejack Menace",
	"Counterflux",
	"Counterlash",
	"Coursers' Accord",
	"Court Street Denizen",
	"Courtly Provocateur",
	"Cower in Fear",
	"Crackling Perimeter",
	"Craterhoof Behemoth",
	"Craterize",
	"Creeping Renaissance",
	"Creepy Doll",
	"Cremate",
	"Crimson Muckwader",
	"Crippling Blight",
	"Crippling Chill",
	"Crocanura",
	"Crosstown Courier",
	"Crossway Vampire",
	"Crowned Ceratok",
	"Crusader of Odric",
	"Crushing Vines",
	"Crypt Creeper",
	"Crypt Ghast",
	"Cryptborn Horror",
	"Curiosity",
	"Curse of Bloodletting",
	"Curse of Death's Hold",
	"Curse of Echoes",
	"Curse of Exhaustion",
	"Curse of Misfortunes",
	"Curse of Oblivion",
	"Curse of Stalked Prey",
	"Curse of the Bloody Tome",
	"Curse of the Nightly Hunt",
	"Curse of the Pierced Heart",
	"Curse of Thirst",
	"Cursebreak",
	"Cyclonic Rift",
	"Daggerdrome Imp",
	"Dangerous Wager",
	"Daring Skyjek",
	"Dark Favor",
	"Dark Impostor",
	"Dark Revenant",
	"Darkthicket Wolf",
	"Dawntreader Elk",
	"Daybreak Ranger",
	"Nightfall Predator",
	"Dead Reveler",
	"Dead Weight",
	"Deadbridge Goliath",
	"Deadeye Navigator",
	"Deadly Allure",
	"Deadly Recluse",
	"Dearly Departed",
	"Death Wind",
	"Death's Approach",
	"Death's Caress",
	"Death's Presence",
	"Deathcult Rogue",
	"Deathpact Angel",
	"Deathrite Shaman",
	"Debtor's Pulpit",
	"Defang",
	"Defy Death",
	"Delver of Secrets",
	"Insectile Aberration",
	"Demolish",
	"Demonic Rising",
	"Demonic Taskmaster",
	"Demonlord of Ashmouth",
	"Demonmail Hauberk",
	"Deranged Assistant",
	"Deranged Outcast",
	"Descendants' Path",
	"Descent into Madness",
	"Desecration Demon",
	"Desolate Lighthouse",
	"Desperate Ravings",
	"Destroy the Evidence",
	"Detention Sphere",
	"Devastation Tide",
	"Deviant Glee",
	"Devil's Play",
	"Devour Flesh",
	"Devout Chaplain",
	"Diabolic Revelation",
	"Diluvian Primordial",
	"Dimir Charm",
	"Dimir Guildgate",
	"Dimir Keyrune",
	"Dinrova Horror",
	"Diregraf Captain",
	"Diregraf Escort",
	"Diregraf Ghoul",
	"Disciple of Bolas",
	"Disciple of Griselbrand",
	"Disciple of the Old Ways",
	"Disentomb",
	"Dispel",
	"Dissipate",
	"Divination",
	"Divine Deflection",
	"Divine Favor",
	"Divine Reckoning",
	"Divine Verdict",
	"Domri Rade",
	"Doomed Traveler",
	"Door to Nothingness",
	"Doorkeeper",
	"Downpour",
	"Downsize",
	"Dragon Hatchling",
	"Dragonskull Summit",
	"Drainpipe Vermin",
	"Drakewing Krasis",
	"Dramatic Rescue",
	"Dread Slaver",
	"Dreadbore",
	"Dreadwaters",
	"Dream Twist",
	"Dreg Mangler",
	"Driver of the Dead",
	"Drogskol Captain",
	"Drogskol Reaver",
	"Drowned Catacomb",
	"Drudge Beetle",
	"Druid's Deliverance",
	"Druid's Familiar",
	"Druids' Repository",
	"Dryad Militant",
	"Dual Casting",
	"Dungeon Geists",
	"Duress",
	"Duskdale Wurm",
	"Duskmantle Guildmage",
	"Duskmantle Prowler",
	"Duskmantle Seer",
	"Dutiful Thrull",
	"Duty-Bound Dead",
	"Dying Wish",
	"Dynacharge",
	"Eaten by Spiders",
	"Elbrus, the Binding Blade",
	"Withengar Unbound",
	"Elder Cathar",
	"Elder of Laurels",
	"Elderscale Wurm",
	"Electrickery",
	"Elgaud Inquisitor",
	"Elgaud Shieldmate",
	"Elite Inquisitor",
	"Elixir of Immortality",
	"Elusive Krasis",
	"Elvish Archdruid",
	"Elvish Visionary",
	"Emancipation Angel",
	"Ember Beast",
	"Encrust",
	"Endless Ranks of the Dead",
	"Enter the Infinite",
	"Entreat the Angels",
	"Epic Experiment",
	"Erase",
	"Erdwal Ripper",
	"Essence Backlash",
	"Essence Drain",
	"Essence Harvest",
	"Essence of the Wild",
	"Essence Scatter",
	"Ethereal Armor",
	"Evernight Shade",
	"Evil Twin",
	"Evolving Wilds",
	"Executioner's Hood",
	"Executioner's Swing",
	"Experiment One",
	"Explosive Impact",
	"Exquisite Blood",
	"Eyes in the Skies",
	"Faerie Impostor",
	"Faerie Invaders",
	"Faith's Reward",
	"Faith's Shield",
	"Faithless Looting",
	"Falkenrath Aristocrat",
	"Falkenrath Exterminator",
	"Falkenrath Marauders",
	"Falkenrath Noble",
	"Falkenrath Torturer",
	"Fall of the Gavel",
	"Farbog Boneflinger",
	"Farbog Explorer",
	"Farseek",
	"Fathom Mage",
	"Favor of the Woods",
	"Favorable Winds",
	"Feed the Pack",
	"Feeling of Dread",
	"Fencing Ace",
	"Feral Ridgewolf",
	"Fervent Cathar",
	"Fervor",
	"Festerhide Boar",
	"Fettergeist",
	"Fiend Hunter",
	"Fiend of the Shadows",
	"Fire Elemental",
	"Firefist Striker",
	"Firemane Avenger",
	"Firemind's Foresight",
	"Fires of Undeath",
	"Firewing Phoenix",
	"Five-Alarm Fire",
	"Flames of the Firebrand",
	"Flayer of the Hatebound",
	"Fleeting Distraction",
	"Fling",
	"Flinthoof Boar",
	"Flowering Lumberknot",
	"Fog",
	"Fog Bank",
	"Forbidden Alchemy",
	"Forced Adaptation",
	"Forest",
	"Forge Devil",
	"Fortress Crab",
	"Fortress Cyclops",
	"Foundry Champion",
	"Foundry Street Denizen",
	"Frenzied Tilling",
	"Frightful Delusion",
	"Frilled Oculus",
	"Frontline Medic",
	"Frostburn Weird",
	"Full Moon's Rise",
	"Fungal Sprouting",
	"Furious Resistance",
	"Furnace Whelp",
	"Furor of the Bitten",
	"Gallows at Willow Hill",
	"Gallows Warden",
	"Galvanic Alchemist",
	"Galvanic Juggernaut",
	"Gang of Devils",
	"Garruk Relentless",
	"Garruk, the Veil-Cursed",
	"Garruk's Packleader",
	"Garruk, Primal Hunter",
	"Gatecreeper Vine",
	"Gateway Shade",
	"Gather the Townsfolk",
	"Gatstaf Shepherd",
	"Gatstaf Howler",
	"Gavony Ironwright",
	"Gavony Township",
	"Geist of Saint Traft",
	"Geist Snatch",
	"Geist Trappers",
	"Geist-Honored Monk",
	"Geistcatcher's Rig",
	"Geistflame",
	"Gem of Becoming",
	"Geralf's Messenger",
	"Geralf's Mindcrusher",
	"Soul Seizer",
	"Ghastly Haunting",
	"Ghor-Clan Rampager",
	"Ghost Quarter",
	"Ghostform",
	"Ghostly Flicker",
	"Ghostly Possession",
	"Ghostly Touch",
	"Ghoulcaller's Bell",
	"Ghoulcaller's Chant",
	"Ghoulflesh",
	"Ghoulraiser",
	"Ghoultree",
	"Giant Adephage",
	"Giant Growth",
	"Giant Scorpion",
	"Gideon, Champion of Justice",
	"Gift of Orzhova",
	"Gilded Lotus",
	"Gisela, Blade of Goldnight",
	"Glacial Fortress",
	"Glaring Spotlight",
	"Gloom Surgeon",
	"Gloomwidow",
	"Glorious Charge",
	"Gnaw to the Bone",
	"Gobbling Ooze",
	"Goblin Arsonist",
	"Goblin Battle Jester",
	"Goblin Electromancer",
	"Goblin Rally",
	"Godless Shrine",
	"Goldnight Commander",
	"Goldnight Redeemer",
	"Golgari Charm",
	"Golgari Decoy",
	"Golgari Guildgate",
	"Golgari Keyrune",
	"Golgari Longlegs",
	"Gore-House Chainwalker",
	"Grafdigger's Cage",
	"Grasp of Phantoms",
	"Grave Betrayal",
	"Grave Bramble",
	"Grave Exchange",
	"Gravecrawler",
	"Gravepurge",
	"Gravetiller Wurm",
	"Graveyard Shovel",
	"Greenside Watcher",
	"Gridlock",
	"Griffin Protector",
	"Grim Backwoods",
	"Grim Flowering",
	"Grim Roustabout",
	"Grimgrin, Corpse-Born",
	"Grimoire of the Dead",
	"Griptide",
	"Griselbrand",
	"Grisly Salvage",
	"Grisly Spectacle",
	"Grizzled Outcasts",
	"Krallenhorde Wantons",
	"Ground Assault",
	"Ground Seal",
	"Grounded",
	"Grove of the Guardian",
	"Growing Ranks",
	"Gruesome Deformity",
	"Gruesome Discovery",
	"Gruul Charm",
	"Gruul Guildgate",
	"Gruul Keyrune",
	"Gruul Ragebeast",
	"Gryff Vanguard",
	"Guardian Lions",
	"Guardian of the Gateless",
	"Guardians of Akrasa",
	"Guild Feud",
	"Guildscorn Ward",
	"Guise of Fire",
	"Gutter Grime",
	"Gutter Skulk",
	"Guttersnipe",
	"Gyre Sage",
	"Hallowed Fountain",
	"Hamlet Captain",
	"Hamletback Goliath",
	"Hands of Binding",
	"Hanweir Lancer",
	"Harbor Bandit",
	"Harbor Serpent",
	"Harrowing Journey",
	"Harvest Pyre",
	"Harvester of Souls",
	"Haunted Fengraf",
	"Haunted Guardian",
	"Havengul Lich",
	"Havengul Runebinder",
	"Havengul Skaab",
	"Havengul Vampire",
	"Havoc Festival",
	"Headless Skaab",
	"Healer of the Pride",
	"Heartless Summoning",
	"Heavy Mattock",
	"Heckling Fiends",
	"Heirs of Stromkirk",
	"Hellhole Flailer",
	"Hellion Crucible",
	"Hellkite Tyrant",
	"Hellraiser Goblin",
	"Hellrider",
	"Helvault",
	"Herald of War",
	"Heretic's Punishment",
	"Heroes' Reunion",
	"High Priest of Penance",
	"Highborn Ghoul",
	"Hindervines",
	"Hinterland Harbor",
	"Hinterland Hermit",
	"Hinterland Scourge",
	"Hold the Gates",
	"Hollowhenge Beast",
	"Hollowhenge Scavenger",
	"Hollowhenge Spirit",
	"Holy Justiciar",
	"Holy Mantle",
	"Homicidal Seclusion",
	"Homing Lightning",
	"Horncaller's Chant",
	"Horror of the Dim",
	"Hound of Griselbrand",
	"Hover Barrier",
	"Howlgeist",
	"Mayor of Avabruck",
	"Howlpack Alpha",
	"Villagers of Estwald",
	"Howlpack of Estwald",
	"Human Frailty",
	"Hunger of the Howlpack",
	"Hunted Ghoul",
	"Huntmaster of the Fells",
	"Ravager of the Fells",
	"Hussar Patrol",
	"Hydroform",
	"Hydrosurge",
	"Hypersonic Dragon",
	"Hysterical Blindness",
	"Illness in the Ranks",
	"Illusionist's Bracers",
	"Immerwolf",
	"Immortal Servitude",
	"Inaction Injunction",
	"Increasing Ambition",
	"Increasing Confusion",
	"Increasing Devotion",
	"Increasing Savagery",
	"Increasing Vengeance",
	"Incursion Specialist",
	"Index",
	"Infernal Plunge",
	"Infinite Reflection",
	"Inquisitor's Flail",
	"Inspiration",
	"Instigator Gang",
	"Wildblood Pack",
	"Intangible Virtue",
	"Into the Maw of Hell",
	"Into the Void",
	"Intrepid Hero",
	"Invisible Stalker",
	"Village Ironsmith",
	"Ironfang",
	"Island",
	"Isolated Chapel",
	"Isperia's Skywatch",
	"Isperia, Supreme Judge",
	"Ivy Lane Denizen",
	"Izzet Charm",
	"Izzet Guildgate",
	"Izzet Keyrune",
	"Izzet Staticaster",
	"Jace's Phantasm",
	"Jace, Architect of Thought",
	"Jace, Memory Adept",
	"Jar of Eyeballs",
	"Jarad's Orders",
	"Jarad, Golgari Lich Lord",
	"Jayemdae Tome",
	"Joint Assault",
	"Judge's Familiar",
	"Keening Apparition",
	"Kessig Cagebreakers",
	"Kessig Malcontents",
	"Kessig Recluse",
	"Kessig Wolf",
	"Kessig Wolf Run",
	"Keymaster Rogue",
	"Killing Glare",
	"Killing Wave",
	"Kindercatch",
	"Kindled Fury",
	"Kingpin's Pet",
	"Kitesail",
	"Knight of Glory",
	"Knight of Infamy",
	"Knight of Obligation",
	"Knight Watch",
	"Knightly Valor",
	"Korozda Guildmage",
	"Korozda Monitor",
	"Kraken Hatchling",
	"Wolfbitten Captive",
	"Krallenhorde Killer",
	"Krenko's Command",
	"Krenko, Mob Boss",
	"Kruin Outlaw",
	"Terror of Kruin Pass",
	"Kruin Striker",
	"Laboratory Maniac",
	"Lair Delve",
	"Lambholt Elder",
	"Silverpelt Werewolf",
	"Lantern Spirit",
	"Last Thoughts",
	"Latch Seeker",
	"Launch Party",
	"Lazav, Dimir Mastermind",
	"Leap of Faith",
	"Legion Loyalist",
	"Leyline Phantom",
	"Lightning Mauler",
	"Lightning Prowess",
	"Liliana of the Dark Realms",
	"Liliana of the Veil",
	"Liliana's Shade",
	"Lingering Souls",
	"Lobber Crew",
	"Lone Revenant",
	"Lord of the Void",
	"Lost in the Mist",
	"Lost in the Woods",
	"Lotleth Troll",
	"Loxodon Smiter",
	"Loyal Cathar",
	"Unhallowed Cathar",
	"Ludevic's Test Subject",
	"Ludevic's Abomination",
	"Lumberknot",
	"Luminate Primordial",
	"Lunar Mystic",
	"Lyev Skyknight",
	"Maalfeld Twins",
	"Mad Prophet",
	"Madcap Skills",
	"Magmaquake",
	"Make a Wish",
	"Makeshift Mauler",
	"Malicious Intent",
	"Malignus",
	"Mana Bloom",
	"Manor Gargoyle",
	"Manor Skeleton",
	"Mark for Death",
	"Mark of Mutiny",
	"Mark of the Vampire",
	"Markov Blademaster",
	"Markov Patrician",
	"Markov Warlord",
	"Marrow Bats",
	"Martial Glory",
	"Martial Law",
	"Mask of Avacyn",
	"Mass Appeal",
	"Massive Raid",
	"Master Biomancer",
	"Master of the Pearl Trident",
	"Mausoleum Guard",
	"Maw of the Mire",
	"Memory's Journey",
	"Mental Agony",
	"Mental Vapors",
	"Mentor of the Meek",
	"Merciless Eviction",
	"Reckless Waif",
	"Merciless Predator",
	"Mercurial Chemister",
	"Merfolk of the Depths",
	"Merfolk of the Pearl Trident",
	"Metropolis Sprite",
	"Midnight Duelist",
	"Midnight Guard",
	"Midnight Haunting",
	"Midnight Recovery",
	"Midvast Protector",
	"Mikaeus, the Lunarch",
	"Mikaeus, the Unhallowed",
	"Millennial Gargoyle",
	"Miming Slime",
	"Mind Grind",
	"Mind Rot",
	"Mind Sculpt",
	"Mindclaw Shaman",
	"Mindeye Drake",
	"Mindshrieker",
	"Minotaur Aggressor",
	"Mirror-Mad Phantasm",
	"Mist Raven",
	"Misthollow Griffin",
	"Mizzium Mortars",
	"Mizzium Skin",
	"Moan of the Unhallowed",
	"Mogg Flunkies",
	"Moldgraf Monstrosity",
	"Molten Primordial",
	"Moment of Heroism",
	"Mondronen Shaman",
	"Tovolar's Magehunter",
	"Moon Heron",
	"Moonlight Geist",
	"Moonmist",
	"Scorned Villager",
	"Moonscarred Werewolf",
	"Moonsilver Spear",
	"Moonveil Dragon",
	"Moorland Haunt",
	"Moorland Inquisitor",
	"Morkrut Banshee",
	"Mortus Strider",
	"Mountain",
	"Mugging",
	"Mulch",
	"Murder",
	"Murder Investigation",
	"Murder of Crows",
	"Mutilate",
	"Mwonvuli Beast Tracker",
	"Mystic Genesis",
	"Mystic Retrieval",
	"Narstad Scrapper",
	"Natural End",
	"Naturalize",
	"Nav Squad Commandos",
	"Nearheath Pilgrim",
	"Nearheath Stalker",
	"Necrobite",
	"Necropolis Regent",
	"Nefarox, Overlord of Grixis",
	"Negate",
	"Nephalia Drownyard",
	"Nephalia Seakite",
	"Nephalia Smuggler",
	"Nettle Swine",
	"Nevermore",
	"New Prahv Guildmage",
	"Niblis of the Breath",
	"Niblis of the Mist",
	"Niblis of the Urn",
	"Nicol Bolas, Planeswalker",
	"Night Revelers",
	"Night Terrors",
	"Nightbird's Clutches",
	"Nightshade Peddler",
	"Nightveil Specter",
	"Nimbus Swimmer",
	"Niv-Mizzet, Dracogenius",
	"Nivix Guildmage",
	"Nivmagus Elemental",
	"Oak Street Innkeeper",
	"Oblivion Ring",
	"Obzedat, Ghost Council",
	"Odric, Master Tactician",
	"Ogre Jailbreaker",
	"Ogre Slumlord",
	"Olivia Voldaren",
	"Omniscience",
	"One Thousand Lashes",
	"One-Eyed Scarecrow",
	"Ooze Flux",
	"Orchard Spirit",
	"Ordruun Veteran",
	"Orzhov Charm",
	"Orzhov Guildgate",
	"Orzhov Keyrune",
	"Otherworld Atlas",
	"Outwit",
	"Overgrown Tomb",
	"Pacifism",
	"Pack Rat",
	"Palisade Giant",
	"Parallel Lives",
	"Paralyzing Grasp",
	"Paranoid Delusions",
	"Paraselene",
	"Past in Flames",
	"Pathbreaker Wurm",
	"Peel from Reality",
	"Perilous Shadow",
	"Phantom General",
	"Phylactery Lich",
	"Phyrexian Hulk",
	"Pillar of Flame",
	"Pillarfield Ox",
	"Pit Fight",
	"Pitchburn Devils",
	"Pithing Needle",
	"Plains",
	"Planar Cleansing",
	"Plummet",
	"Polluted Dead",
	"Precinct Captain",
	"Predator Ooze",
	"Predator's Gambit",
	"Predator's Rapport",
	"Predatory Rampage",
	"Prey Upon",
	"Primal Clay",
	"Primal Huntbeast",
	"Primal Surge",
	"Primal Visitation",
	"Prime Speaker Zegana",
	"Primordial Hydra",
	"Prized Elephant",
	"Prophetic Prism",
	"Psychic Spiral",
	"Psychic Strike",
	"Public Execution",
	"Purge the Profane",
	"Purify the Grave",
	"Pursuit of Flight",
	"Pyreheart Wolf",
	"Pyroconvergence",
	"Quirion Dryad",
	"Racecourse Fury",
	"Rage Thrower",
	"Raging Poltergeist",
	"Rain of Blades",
	"Rain of Thorns",
	"Rakdos Cackler",
	"Rakdos Charm",
	"Rakdos Guildgate",
	"Rakdos Keyrune",
	"Rakdos Ragemutt",
	"Rakdos Ringleader",
	"Rakdos Shred-Freak",
	"Rakdos's Return",
	"Rakdos, Lord of Riots",
	"Rakish Heir",
	"Rally the Peasants",
	"Tormented Pariah",
	"Rampaging Werewolf",
	"Rancor",
	"Ranger's Guile",
	"Ranger's Path",
	"Rapid Hybridization",
	"Ravenous Rats",
	"Ray of Revelation",
	"Razortip Whip",
	"Realmwright",
	"Reap the Seagraf",
	"Reaper from the Abyss",
	"Rebuke",
	"Reckless Brute",
	"Redirect",
	"Reforge the Soul",
	"Relentless Skaabs",
	"Reliquary Tower",
	"Renegade Demon",
	"Requiem Angel",
	"Rest in Peace",
	"Restoration Angel",
	"Revenge of the Hunted",
	"Reverberate",
	"Revive",
	"Rewind",
	"Rhox Faithmender",
	"Riders of Gavony",
	"Righteous Authority",
	"Righteous Blow",
	"Righteous Charge",
	"Ring of Evos Isle",
	"Ring of Kalonia",
	"Ring of Thune",
	"Ring of Valkas",
	"Ring of Xathrid",
	"Riot Devils",
	"Riot Gear",
	"Riot Ringleader",
	"Ripscale Predator",
	"Rise from the Grave",
	"Risen Sanctuary",
	"Rite of Ruin",
	"Rites of Reaping",
	"Rix Maadi Guildmage",
	"Roaring Primadox",
	"Rogue's Passage",
	"Rolling Temblor",
	"Rooftop Storm",
	"Rootborn Defenses",
	"Rootbound Crag",
	"Rotcrown Ghoul",
	"Rotting Fensnake",
	"Rubbleback Rhino",
	"Rubblebelt Raiders",
	"Rubblehulk",
	"Ruination Wurm",
	"Rummaging Goblin",
	"Runechanter's Pike",
	"Runewing",
	"Runic Repetition",
	"Rush of Blood",
	"Russet Wolves",
	"Rust Scarab",
	"Sacred Foundry",
	"Safe Passage",
	"Sage's Row Denizen",
	"Sanctuary Cat",
	"Sands of Delirium",
	"Sapphire Drake",
	"Savage Surge",
	"Saving Grasp",
	"Scab-Clan Charger",
	"Scalding Devil",
	"Scatter Arc",
	"Scorch the Fields",
	"Scorchwalker",
	"Scourge of Geier Reach",
	"Scrapskin Drake",
	"Screeching Bat",
	"Stalking Vampire",
	"Screeching Skaab",
	"Scroll of Avacyn",
	"Scroll of Griselbrand",
	"Scroll Thief",
	"Seance",
	"Search the City",
	"Search Warrant",
	"Searchlight Geist",
	"Searing Spear",
	"Second Guess",
	"Secrets of the Dead",
	"Security Blockade",
	"Seek the Horizon",
	"Selesnya Charm",
	"Selesnya Guildgate",
	"Selesnya Keyrune",
	"Selesnya Sentry",
	"Selfless Cathar",
	"Selhoff Occultist",
	"Seller of Songbirds",
	"Sensory Deprivation",
	"Sentinel Spider",
	"Sepulchral Primordial",
	"Seraph of Dawn",
	"Seraph Sanctuary",
	"Serene Remembrance",
	"Serpent's Gift",
	"Serra Angel",
	"Serra Avatar",
	"Serra Avenger",
	"Servant of Nefarox",
	"Sever the Bloodline",
	"Sewer Shambler",
	"Shadow Alley Denizen",
	"Shadow Slice",
	"Shambleshark",
	"Sharpened Pitchfork",
	"Shattered Perception",
	"Shattering Blow",
	"Sheltering Word",
	"Shielded Passage",
	"Shimian Specter",
	"Shimmering Grotto",
	"Show of Valor",
	"Shriekgeist",
	"Shrieking Affliction",
	"Sigarda, Host of Herons",
	"Sightless Ghoul",
	"Sign in Blood",
	"Signal the Clans",
	"Silent Departure",
	"Silklash Spider",
	"Silver-Inlaid Dagger",
	"Silverblade Paladin",
	"Silverchase Fox",
	"Silverclaw Griffin",
	"Silvercoat Lion",
	"Simic Charm",
	"Simic Fluxmage",
	"Simic Guildgate",
	"Simic Keyrune",
	"Simic Manipulator",
	"Skaab Goliath",
	"Skaab Ruinator",
	"Skarrg Goliath",
	"Skarrg Guildmage",
	"Skeletal Grimace",
	"Skillful Lunge",
	"Skinbrand Goblin",
	"Skirsdag Cultist",
	"Skirsdag Flayer",
	"Skirsdag High Priest",
	"Skull Rend",
	"Skullcrack",
	"Skyblinder Staff",
	"Skygames",
	"Skyknight Legionnaire",
	"Skyline Predator",
	"Skymark Roc",
	"Slate Street Ruffian",
	"Slaughter Games",
	"Slaughterhorn",
	"Slayer of the Wicked",
	"Slayers' Stronghold",
	"Sleep",
	"Slime Molding",
	"Slitherhead",
	"Sluiceway Scorpion",
	"Slum Reaper",
	"Slumbering Dragon",
	"Smelt",
	"Smite",
	"Smite the Monstrous",
	"Smog Elemental",
	"Snapcaster Mage",
	"Snare the Skies",
	"Somberwald Dryad",
	"Somberwald Sage",
	"Somberwald Spider",
	"Somberwald Vigilante",
	"Sorin, Lord of Innistrad",
	"Soul of the Harvest",
	"Soul Ransom",
	"Soul Tithe",
	"Soulcage Fiend",
	"Soulsworn Spirit",
	"Spare from Evil",
	"Spark Trooper",
	"Spawn of Rix Maadi",
	"Spectral Flight",
	"Spectral Gateguards",
	"Spectral Prison",
	"Spectral Rider",
	"Spell Rupture",
	"Spelltwine",
	"Sphere of Safety",
	"Sphinx of the Chimes",
	"Sphinx of Uthuun",
	"Sphinx's Revelation",
	"Spider Spawning",
	"Spidery Grasp",
	"Spiked Baloth",
	"Spire Tracer",
	"Spirit Away",
	"Spiteful Shadows",
	"Splatter Thug",
	"Splinterfright",
	"Stab Wound",
	"Staff of Nin",
	"Stealer of Secrets",
	"Steam Vents",
	"Stensia Bloodhall",
	"Stern Mentor",
	"Stitched Drake",
	"Stitcher's Apprentice",
	"Stolen Goods",
	"Stolen Identity",
	"Stomping Ground",
	"Stonefare Crocodile",
	"Stonewright",
	"Stony Silence",
	"Stormbound Geist",
	"Stormtide Leviathan",
	"Strangleroot Geist",
	"Street Spasm",
	"Street Sweeper",
	"Stromkirk Captain",
	"Stromkirk Noble",
	"Stromkirk Patrol",
	"Structural Collapse",
	"Stuffy Doll",
	"Sturmgeist",
	"Sublime Archangel",
	"Sudden Disappearance",
	"Sulfur Falls",
	"Sundering Growth",
	"Sunhome Guildmage",
	"Sunpetal Grove",
	"Sunspire Griffin",
	"Supreme Verdict",
	"Survey the Wreckage",
	"Swamp",
	"Swift Justice",
	"Switcheroo",
	"Sylvan Primordial",
	"Syncopate",
	"Syndic of Tithes",
	"Syndicate Enforcer",
	"Tablet of the Guilds",
	"Talons of Falkenrath",
	"Talrand's Invocation",
	"Talrand, Sky Summoner",
	"Tamiyo, the Moon Sage",
	"Tandem Lookout",
	"Tavern Swindler",
	"Teleportal",
	"Temple Garden",
	"Temporal Mastery",
	"Tenement Crasher",
	"Terminus",
	"Terrifying Presence",
	"Terrus Wurm",
	"Thalia, Guardian of Thraben",
	"Thatcher Revolt",
	"Thespian's Stage",
	"Think Twice",
	"Thought Scour",
	"Thoughtflare",
	"Thraben Doomsayer",
	"Thraben Heretic",
	"Thraben Sentry",
	"Thraben Militia",
	"Thraben Purebloods",
	"Thraben Valiant",
	"Thragtusk",
	"Thrill-Kill Assassin",
	"Thrull Parasite",
	"Thunderbolt",
	"Thundermaw Hellkite",
	"Thunderous Wrath",
	"Tibalt, the Fiend-Blooded",
	"Timberland Guide",
	"Timberpack Wolf",
	"Tin Street Market",
	"Titanic Growth",
	"Torch Fiend",
	"Tormented Soul",
	"Tormentor's Trident",
	"Tormod's Crypt",
	"Totally Lost",
	"Touch of the Eternal",
	"Tower Defense",
	"Tower Drake",
	"Tower Geist",
	"Towering Indrik",
	"Towering Thunderfist",
	"Tracker's Instincts",
	"Trading Post",
	"Tragic Slip",
	"Trained Caracal",
	"Traitorous Blood",
	"Traitorous Instinct",
	"Transguild Promenade",
	"Travel Preparations",
	"Traveler's Amulet",
	"Treacherous Pit-Dweller",
	"Treasured Find",
	"Treasury Thrull",
	"Tree of Redemption",
	"Trepanation Blade",
	"Trestle Troll",
	"Tribute to Hunger",
	"Tricks of the Trade",
	"Triumph of Cruelty",
	"Triumph of Ferocity",
	"Trostani's Judgment",
	"Trostani, Selesnya's Voice",
	"Truefire Paladin",
	"Trumpet Blast",
	"Trusted Forcemage",
	"Turn to Slag",
	"Typhoid Rats",
	"Tyrant of Discord",
	"Ultimate Price",
	"Ulvenwald Bear",
	"Ulvenwald Mystics",
	"Ulvenwald Primordials",
	"Ulvenwald Tracker",
	"Unbreathing Horde",
	"Unburial Rites",
	"Uncanny Speed",
	"Undead Alchemist",
	"Undead Executioner",
	"Undercity Informer",
	"Undercity Plague",
	"Underworld Connections",
	"Undying Evil",
	"Unexpected Results",
	"Unhallowed Pact",
	"Unruly Mob",
	"Unsummon",
	"Urban Burgeoning",
	"Urban Evolution",
	"Urbis Protector",
	"Urgent Exorcism",
	"Utvara Hellkite",
	"Vampire Interloper",
	"Vampire Nighthawk",
	"Vampire Nocturnus",
	"Vampiric Fury",
	"Vandalblast",
	"Vanguard's Shield",
	"Vanishment",
	"Vassal Soul",
	"Vastwood Gorger",
	"Vault of the Archangel",
	"Vedalken Entrancer",
	"Veilborn Ghoul",
	"Vengeful Vampire",
	"Verdant Haven",
	"Vessel of Endless Rest",
	"Vexing Devil",
	"Viashino Racketeer",
	"Viashino Shanktail",
	"Victim of Night",
	"Vigilante Justice",
	"Vile Rebirth",
	"Village Bell-Ringer",
	"Village Cannibals",
	"Village Survivors",
	"Vitu-Ghazi Guildmage",
	"Vizkopa Confessor",
	"Vizkopa Guildmage",
	"Voice of the Provinces",
	"Voiceless Spirit",
	"Void Stalker",
	"Voidwalk",
	"Voidwielder",
	"Volatile Rig",
	"Volcanic Geyser",
	"Volcanic Strength",
	"Vorapede",
	"Vorstclaw",
	"Vraska the Unseen",
	"Wakedancer",
	"Walking Corpse",
	"Wall of Fire",
	"Wandering Wolf",
	"War Falcon",
	"War Priest of Thune",
	"Warclamp Mastiff",
	"Warden of the Wall",
	"Warmind Infantry",
	"Wasteland Viper",
	"Watercourser",
	"Watery Grave",
	"Way of the Thief",
	"Wayfaring Temple",
	"Welkin Tern",
	"Afflicted Deserter",
	"Werewolf Ransacker",
	"Whispering Madness",
	"Wight of Precinct Six",
	"Wild Beastmaster",
	"Wild Defiance",
	"Wild Guess",
	"Wild Hunger",
	"Wildwood Geist",
	"Wildwood Rebirth",
	"Wind Drake",
	"Wingcrafter",
	"Wit's End",
	"Witchbane Orb",
	"Wojek Halberdiers",
	"Wolfhunter's Quiver",
	"Wolfir Avenger",
	"Wolfir Silverheart",
	"Wooden Stake",
	"Woodland Cemetery",
	"Woodland Sleuth",
	"Worldfire",
	"Worldspine Wurm",
	"Wrack with Madness",
	"Wreath of Geists",
	"Wrecking Ogre",
	"Xathrid Gorgon",
	"Yeva's Forcemage",
	"Yeva, Nature's Herald",
	"Yew Spirit",
	"Young Wolf",
	"Zameck Guildmage",
	"Zanikev Locust",
	"Zarichi Tiger",
	"Zealous Conscripts",
	"Zealous Strike",
	"Zhur-Taa Swine",
	"Zombie Apocalypse",
	"Zombie Goliath"
];
