var standards = [
	/Abattoir\sGhoul/,
	/Abbey\sGriffin/,
	/Abrupt\sDecay/,
	/Abundant\sGrowth/,
	/Acidic\sSlime/,
	/Aerial\sPredation/,
	/Aggravate/,
	/Ajani's\sSunstriker/,
	/Ajani,\sCaller of the Pride/,
	/Akroma's\sMemorial/,
	/Alchemist's\sApprentice/,
	/Alchemist's\sRefuge/,
	/Alpha\sBrawl/,
	/Altar\sof the Lost/,
	/Altar's\sReap/,
	/Amass\sthe Components/,
	/Ambush\sViper/,
	/Ancient\sGrudge/,
	/Angel\sof Flight Alabaster/,
	/Angel\sof Glory's Rise/,
	/Angel\sof Jubilation/,
	/Angel\sof Serenity/,
	/Angel's\sMercy/,
	/Angel's\sTomb/,
	/Angelic\sArmaments/,
	/Angelic\sBenediction/,
	/Angelic\sOverseer/,
	/Angelic\sWall/,
	/Annihilating\sFire/,
	/Appetite\sfor Brains/,
	/Aquus\sSteed/,
	/Arbor\sElf/,
	/Arcane\sMelee/,
	/Archaeomancer/,
	/Archangel/,
	/Archangel's\sLight/,
	/Ravenous\sDemon/,
	/Archdemon\sof Greed/,
	/Archon\sof the Triumvirate/,
	/Archweaver/,
	/Archwing\sDragon/,
	/Arctic\sAven/,
	/Armada\sWurm/,
	/Armored\sSkaab/,
	/Armory\sGuard/,
	/Arms\sDealer/,
	/Army\sof the Damned/,
	/Arrest/,
	/Artful\sDodge/,
	/Ash\sZealot/,
	/Ashmouth\sHound/,
	/Assassin's\sStrike/,
	/Attended\sKnight/,
	/Auger\sSpree/,
	/Augur\sof Bolas/,
	/Avacyn's\sCollar/,
	/Avacyn's\sPilgrim/,
	/Avacyn,\sAngel of Hope/,
	/Avacynian\sPriest/,
	/Aven\sSquire/,
	/Avenging\sArrow/,
	/Axebane\sGuardian/,
	/Axebane\sStag/,
	/Azor's\sElocutors/,
	/Azorius\sArrester/,
	/Azorius\sCharm/,
	/Azorius\sGuildgate/,
	/Azorius\sJusticiar/,
	/Azorius\sKeyrune/,
	/Back\sfrom the Brink/,
	/Balefire\sDragon/,
	/Hanweir\sWatchkeep/,
	/Bane\sof Hanweir/,
	/Banishing\sStroke/,
	/Banners\sRaised/,
	/Bar\sthe Door/,
	/Barter\sin Blood/,
	/Batterhorn/,
	/Battle\sHymn/,
	/Battle\sof Wits/,
	/Battleflight\sEagle/,
	/Battleground\sGeist/,
	/Bazaar\sKrovod/,
	/Beguiler\sof Wills/,
	/Bellows\sLizard/,
	/Bitterheart\sWitch/,
	/Black\sCat/,
	/Bladed\sBracers/,
	/Bladetusk\sBoar/,
	/Blasphemous\sAct/,
	/Blazing\sTorch/,
	/Blessings\sof Nature/,
	/Blistercoil\sWeird/,
	/Blood\sArtist/,
	/Blood\sCrypt/,
	/Blood\sFeud/,
	/Blood\sReckoning/,
	/Bloodcrazed\sNeonate/,
	/Bloodflow\sConnoisseur/,
	/Bloodfray\sGiant/,
	/Bloodgift\sDemon/,
	/Bloodhunter\sBat/,
	/Bloodline\sKeeper/,
	/Lord\sof Lineage/,
	/Bloodthrone\sVampire/,
	/Blustersquall/,
	/Bond\sBeetle/,
	/Bonds\sof Faith/,
	/Bone\sSplinters/,
	/Bone\sto Ash/,
	/Boneyard\sWurm/,
	/Bonfire\sof the Damned/,
	/Borderland\sRanger/,
	/Boundless\sRealms/,
	/Bountiful\sHarvest/,
	/Bower\sPassage/,
	/Brain\sWeevil/,
	/Bramblecrush/,
	/Break\sof Day/,
	/Briarpack\sAlpha/,
	/Brimstone\sVolley/,
	/Bruna,\sLight of Alabaster/,
	/Brushstrider/,
	/Builder's\sBlessing/,
	/Bump\sin the Night/,
	/Burden\sof Guilt/,
	/Burn\sat the Stake/,
	/Burning\sOil/,
	/Burning\sVengeance/,
	/Butcher\sGhoul/,
	/Butcher's\sCleaver/,
	/Cackling\sCounterpart/,
	/Call\sof the Conclave/,
	/Call\sto Serve/,
	/Call\sto the Kindred/,
	/Cancel/,
	/Canyon\sMinotaur/,
	/Captain\sof the Mists/,
	/Captain\sof the Watch/,
	/Captain's\sCall/,
	/Caravan\sVigil/,
	/Carnival\sHellsteed/,
	/Catacomb\sSlug/,
	/Cathars'\sCrusade/,
	/Cathedral\sof War/,
	/Cathedral\sSanctifier/,
	/Cavern\sof Souls/,
	/Cellar\sDoor/,
	/Centaur\sCourser/,
	/Centaur\sHealer/,
	/Centaur's\sHerald/,
	/Chalice\sof Life/,
	/Chalice\sof Death/,
	/Champion\sof Lambholt/,
	/Champion\sof the Parish/,
	/Chandra's\sFury/,
	/Chandra,\sthe Firebrand/,
	/Chant\sof the Skifsang/,
	/Chaos\sImps/,
	/Chapel\sGeist/,
	/Charmbreaker\sDevils/,
	/Chemister's\sTrick/,
	/Chill\sof Foreboding/,
	/Chorus\sof Might/,
	/Chosen\sof Markov/,
	/Markov's\sServant/,
	/Chromatic\sLantern/,
	/Chronic\sFlooding/,
	/Chronomaton/,
	/Civic\sSaber/,
	/Civilized\sScholar/,
	/Homicidal\sBrute/,
	/Claustrophobia/,
	/Cleaver\sRiot/,
	/Clifftop\sRetreat/,
	/Clinging\sMists/,
	/Clock\sof Omens/,
	/Cloistered\sYouth/,
	/Unholy\sFiend/,
	/Clone/,
	/Cloudshift/,
	/Cobblebrute/,
	/Cobbled\sWings/,
	/Codex\sShredder/,
	/Collective\sBlessing/,
	/Commander's\sAuthority/,
	/Common\sBond/,
	/Concordia\sPegasus/,
	/Conjured\sCurrency/,
	/Conjurer's\sCloset/,
	/Corpse\sLunge/,
	/Corpse\sTraders/,
	/Corpsejack\sMenace/,
	/Counterflux/,
	/Counterlash/,
	/Coursers'\sAccord/,
	/Courtly\sProvocateur/,
	/Cower\sin Fear/,
	/Craterhoof\sBehemoth/,
	/Craterize/,
	/Creeping\sRenaissance/,
	/Creepy\sDoll/,
	/Cremate/,
	/Crimson\sMuckwader/,
	/Crippling\sBlight/,
	/Crippling\sChill/,
	/Crosstown\sCourier/,
	/Crossway\sVampire/,
	/Crusader\sof Odric/,
	/Crushing\sVines/,
	/Crypt\sCreeper/,
	/Cryptborn\sHorror/,
	/Curiosity/,
	/Curse\sof Bloodletting/,
	/Curse\sof Death's Hold/,
	/Curse\sof Echoes/,
	/Curse\sof Exhaustion/,
	/Curse\sof Misfortunes/,
	/Curse\sof Oblivion/,
	/Curse\sof Stalked Prey/,
	/Curse\sof the Bloody Tome/,
	/Curse\sof the Nightly Hunt/,
	/Curse\sof the Pierced Heart/,
	/Curse\sof Thirst/,
	/Cursebreak/,
	/Cyclonic\sRift/,
	/Daggerdrome\sImp/,
	/Dangerous\sWager/,
	/Dark\sFavor/,
	/Dark\sImpostor/,
	/Dark\sRevenant/,
	/Darkthicket\sWolf/,
	/Dawntreader\sElk/,
	/Daybreak\sRanger/,
	/Nightfall\sPredator/,
	/Dead\sReveler/,
	/Dead\sWeight/,
	/Deadbridge\sGoliath/,
	/Deadeye\sNavigator/,
	/Deadly\sAllure/,
	/Deadly\sRecluse/,
	/Dearly\sDeparted/,
	/Death\sWind/,
	/Death's\sCaress/,
	/Death's\sPresence/,
	/Deathrite\sShaman/,
	/Defang/,
	/Defy\sDeath/,
	/Delver\sof Secrets/,
	/Insectile\sAberration/,
	/Demolish/,
	/Demonic\sRising/,
	/Demonic\sTaskmaster/,
	/Demonlord\sof Ashmouth/,
	/Demonmail\sHauberk/,
	/Deranged\sAssistant/,
	/Deranged\sOutcast/,
	/Descendants'\sPath/,
	/Descent\sinto Madness/,
	/Desecration\sDemon/,
	/Desolate\sLighthouse/,
	/Desperate\sRavings/,
	/Destroy\sthe Evidence/,
	/Detention\sSphere/,
	/Devastation\sTide/,
	/Deviant\sGlee/,
	/Devil's\sPlay/,
	/Devout\sChaplain/,
	/Diabolic\sRevelation/,
	/Diregraf\sCaptain/,
	/Diregraf\sEscort/,
	/Diregraf\sGhoul/,
	/Disciple\sof Bolas/,
	/Disciple\sof Griselbrand/,
	/Disentomb/,
	/Dispel/,
	/Dissipate/,
	/Divination/,
	/Divine\sDeflection/,
	/Divine\sFavor/,
	/Divine\sReckoning/,
	/Divine\sVerdict/,
	/Doomed\sTraveler/,
	/Door\sto Nothingness/,
	/Doorkeeper/,
	/Downpour/,
	/Downsize/,
	/Dragon\sHatchling/,
	/Dragonskull\sSummit/,
	/Drainpipe\sVermin/,
	/Dramatic\sRescue/,
	/Dread\sSlaver/,
	/Dreadbore/,
	/Dreadwaters/,
	/Dream\sTwist/,
	/Dreg\sMangler/,
	/Driver\sof the Dead/,
	/Drogskol\sCaptain/,
	/Drogskol\sReaver/,
	/Drowned\sCatacomb/,
	/Drudge\sBeetle/,
	/Druid's\sDeliverance/,
	/Druid's\sFamiliar/,
	/Druids'\sRepository/,
	/Dryad\sMilitant/,
	/Dual\sCasting/,
	/Dungeon\sGeists/,
	/Duress/,
	/Duskdale\sWurm/,
	/Duskmantle\sProwler/,
	/Duty-Bound\sDead/,
	/Dynacharge/,
	/Eaten\sby Spiders/,
	/Elbrus,\sthe Binding Blade/,
	/Withengar\sUnbound/,
	/Elder\sCathar/,
	/Elder\sof Laurels/,
	/Elderscale\sWurm/,
	/Electrickery/,
	/Elgaud\sInquisitor/,
	/Elgaud\sShieldmate/,
	/Elite\sInquisitor/,
	/Elixir\sof Immortality/,
	/Elvish\sArchdruid/,
	/Elvish\sVisionary/,
	/Emancipation\sAngel/,
	/Encrust/,
	/Endless\sRanks of the Dead/,
	/Entreat\sthe Angels/,
	/Epic\sExperiment/,
	/Erase/,
	/Erdwal\sRipper/,
	/Essence\sBacklash/,
	/Essence\sDrain/,
	/Essence\sHarvest/,
	/Essence\sof the Wild/,
	/Essence\sScatter/,
	/Ethereal\sArmor/,
	/Evernight\sShade/,
	/Evil\sTwin/,
	/Evolving\sWilds/,
	/Executioner's\sHood/,
	/Explosive\sImpact/,
	/Exquisite\sBlood/,
	/Eyes\sin the Skies/,
	/Faerie\sImpostor/,
	/Faerie\sInvaders/,
	/Faith's\sReward/,
	/Faith's\sShield/,
	/Faithless\sLooting/,
	/Falkenrath\sAristocrat/,
	/Falkenrath\sExterminator/,
	/Falkenrath\sMarauders/,
	/Falkenrath\sNoble/,
	/Falkenrath\sTorturer/,
	/Fall\sof the Gavel/,
	/Farbog\sBoneflinger/,
	/Farbog\sExplorer/,
	/Farseek/,
	/Favor\sof the Woods/,
	/Favorable\sWinds/,
	/Feed\sthe Pack/,
	/Feeling\sof Dread/,
	/Fencing\sAce/,
	/Feral\sRidgewolf/,
	/Fervent\sCathar/,
	/Fervor/,
	/Festerhide\sBoar/,
	/Fettergeist/,
	/Fiend\sHunter/,
	/Fiend\sof the Shadows/,
	/Fire\sElemental/,
	/Firemind's\sForesight/,
	/Fires\sof Undeath/,
	/Firewing\sPhoenix/,
	/Flames\sof the Firebrand/,
	/Flayer\sof the Hatebound/,
	/Fleeting\sDistraction/,
	/Fling/,
	/Flinthoof\sBoar/,
	/Flowering\sLumberknot/,
	/Fog/,
	/Fog\sBank/,
	/Forbidden\sAlchemy/,
	/Forest/,
	/Forge\sDevil/,
	/Fortress\sCrab/,
	/Frightful\sDelusion/,
	/Frostburn\sWeird/,
	/Full\sMoon's Rise/,
	/Fungal\sSprouting/,
	/Furnace\sWhelp/,
	/Furor\sof the Bitten/,
	/Gallows\sat Willow Hill/,
	/Gallows\sWarden/,
	/Galvanic\sAlchemist/,
	/Galvanic\sJuggernaut/,
	/Gang\sof Devils/,
	/Garruk\sRelentless/,
	/Garruk,\sthe Veil-Cursed/,
	/Garruk's\sPackleader/,
	/Garruk,\sPrimal Hunter/,
	/Gatecreeper\sVine/,
	/Gather\sthe Townsfolk/,
	/Gatstaf\sShepherd/,
	/Gatstaf\sHowler/,
	/Gavony\sIronwright/,
	/Gavony\sTownship/,
	/Geist\sof Saint Traft/,
	/Geist\sSnatch/,
	/Geist\sTrappers/,
	/Geist-Honored\sMonk/,
	/Geistcatcher's\sRig/,
	/Geistflame/,
	/Gem\sof Becoming/,
	/Geralf's\sMessenger/,
	/Geralf's\sMindcrusher/,
	/Soul\sSeizer/,
	/Ghastly\sHaunting/,
	/Ghost\sQuarter/,
	/Ghostform/,
	/Ghostly\sFlicker/,
	/Ghostly\sPossession/,
	/Ghostly\sTouch/,
	/Ghoulcaller's\sBell/,
	/Ghoulcaller's\sChant/,
	/Ghoulflesh/,
	/Ghoulraiser/,
	/Ghoultree/,
	/Giant\sGrowth/,
	/Giant\sScorpion/,
	/Gilded\sLotus/,
	/Gisela,\sBlade of Goldnight/,
	/Glacial\sFortress/,
	/Gloom\sSurgeon/,
	/Gloomwidow/,
	/Glorious\sCharge/,
	/Gnaw\sto the Bone/,
	/Gobbling\sOoze/,
	/Goblin\sArsonist/,
	/Goblin\sBattle Jester/,
	/Goblin\sElectromancer/,
	/Goblin\sRally/,
	/Goldnight\sCommander/,
	/Goldnight\sRedeemer/,
	/Golgari\sCharm/,
	/Golgari\sDecoy/,
	/Golgari\sGuildgate/,
	/Golgari\sKeyrune/,
	/Golgari\sLonglegs/,
	/Gore-House\sChainwalker/,
	/Grafdigger's\sCage/,
	/Grasp\sof Phantoms/,
	/Grave\sBetrayal/,
	/Grave\sBramble/,
	/Grave\sExchange/,
	/Gravecrawler/,
	/Gravepurge/,
	/Gravetiller\sWurm/,
	/Graveyard\sShovel/,
	/Griffin\sProtector/,
	/Grim\sBackwoods/,
	/Grim\sFlowering/,
	/Grim\sRoustabout/,
	/Grimgrin,\sCorpse-Born/,
	/Grimoire\sof the Dead/,
	/Griptide/,
	/Griselbrand/,
	/Grisly\sSalvage/,
	/Grizzled\sOutcasts/,
	/Krallenhorde\sWantons/,
	/Ground\sSeal/,
	/Grounded/,
	/Grove\sof the Guardian/,
	/Growing\sRanks/,
	/Gruesome\sDeformity/,
	/Gruesome\sDiscovery/,
	/Gryff\sVanguard/,
	/Guardian\sLions/,
	/Guardians\sof Akrasa/,
	/Guild\sFeud/,
	/Guise\sof Fire/,
	/Gutter\sGrime/,
	/Guttersnipe/,
	/Hallowed\sFountain/,
	/Hamlet\sCaptain/,
	/Hamletback\sGoliath/,
	/Hanweir\sLancer/,
	/Harbor\sBandit/,
	/Harbor\sSerpent/,
	/Harrowing\sJourney/,
	/Harvest\sPyre/,
	/Harvester\sof Souls/,
	/Haunted\sFengraf/,
	/Haunted\sGuardian/,
	/Havengul\sLich/,
	/Havengul\sRunebinder/,
	/Havengul\sSkaab/,
	/Havengul\sVampire/,
	/Havoc\sFestival/,
	/Headless\sSkaab/,
	/Healer\sof the Pride/,
	/Heartless\sSummoning/,
	/Heavy\sMattock/,
	/Heckling\sFiends/,
	/Heirs\sof Stromkirk/,
	/Hellhole\sFlailer/,
	/Hellion\sCrucible/,
	/Hellrider/,
	/Helvault/,
	/Herald\sof War/,
	/Heretic's\sPunishment/,
	/Heroes'\sReunion/,
	/Highborn\sGhoul/,
	/Hinterland\sHarbor/,
	/Hinterland\sHermit/,
	/Hinterland\sScourge/,
	/Hollowhenge\sBeast/,
	/Hollowhenge\sScavenger/,
	/Hollowhenge\sSpirit/,
	/Holy\sJusticiar/,
	/Homicidal\sSeclusion/,
	/Horncaller's\sChant/,
	/Hound\sof Griselbrand/,
	/Hover\sBarrier/,
	/Howlgeist/,
	/Mayor\sof Avabruck/,
	/Howlpack\sAlpha/,
	/Villagers\sof Estwald/,
	/Howlpack\sof Estwald/,
	/Human\sFrailty/,
	/Hunger\sof the Howlpack/,
	/Hunted\sGhoul/,
	/Huntmaster\sof the Fells/,
	/Ravager\sof the Fells/,
	/Hussar\sPatrol/,
	/Hydrosurge/,
	/Hypersonic\sDragon/,
	/Hysterical\sBlindness/,
	/Immerwolf/,
	/Inaction\sInjunction/,
	/Increasing\sAmbition/,
	/Increasing\sConfusion/,
	/Increasing\sDevotion/,
	/Increasing\sSavagery/,
	/Increasing\sVengeance/,
	/Index/,
	/Infernal\sPlunge/,
	/Infinite\sReflection/,
	/Inquisitor's\sFlail/,
	/Inspiration/,
	/Instigator\sGang/,
	/Wildblood\sPack/,
	/Intangible\sVirtue/,
	/Into\sthe Maw of Hell/,
	/Into\sthe Void/,
	/Intrepid\sHero/,
	/Invisible\sStalker/,
	/Village\sIronsmith/,
	/Ironfang/,
	/Island/,
	/Isolated\sChapel/,
	/Isperia's\sSkywatch/,
	/Isperia,\sSupreme Judge/,
	/Izzet\sCharm/,
	/Izzet\sGuildgate/,
	/Izzet\sKeyrune/,
	/Izzet\sStaticaster/,
	/Jace's\sPhantasm/,
	/Jace,\sArchitect of Thought/,
	/Jace,\sMemory Adept/,
	/Jar\sof Eyeballs/,
	/Jarad's\sOrders/,
	/Jarad,\sGolgari Lich Lord/,
	/Jayemdae\sTome/,
	/Joint\sAssault/,
	/Judge's\sFamiliar/,
	/Keening\sApparition/,
	/Kessig\sCagebreakers/,
	/Kessig\sMalcontents/,
	/Kessig\sRecluse/,
	/Kessig\sWolf/,
	/Kessig\sWolf Run/,
	/Killing\sWave/,
	/Kindercatch/,
	/Kindled\sFury/,
	/Kitesail/,
	/Knight\sof Glory/,
	/Knight\sof Infamy/,
	/Knightly\sValor/,
	/Korozda\sGuildmage/,
	/Korozda\sMonitor/,
	/Kraken\sHatchling/,
	/Wolfbitten\sCaptive/,
	/Krallenhorde\sKiller/,
	/Krenko's\sCommand/,
	/Krenko,\sMob Boss/,
	/Kruin\sOutlaw/,
	/Terror\sof Kruin Pass/,
	/Kruin\sStriker/,
	/Laboratory\sManiac/,
	/Lair\sDelve/,
	/Lambholt\sElder/,
	/Silverpelt\sWerewolf/,
	/Lantern\sSpirit/,
	/Latch\sSeeker/,
	/Launch\sParty/,
	/Leap\sof Faith/,
	/Lightning\sMauler/,
	/Lightning\sProwess/,
	/Liliana\sof the Dark Realms/,
	/Liliana\sof the Veil/,
	/Liliana's\sShade/,
	/Lingering\sSouls/,
	/Lobber\sCrew/,
	/Lone\sRevenant/,
	/Lost\sin the Mist/,
	/Lost\sin the Woods/,
	/Lotleth\sTroll/,
	/Loxodon\sSmiter/,
	/Loyal\sCathar/,
	/Unhallowed\sCathar/,
	/Ludevic's\sTest Subject/,
	/Ludevic's\sAbomination/,
	/Lumberknot/,
	/Lunar\sMystic/,
	/Lyev\sSkyknight/,
	/Maalfeld\sTwins/,
	/Mad\sProphet/,
	/Magmaquake/,
	/Make\sa Wish/,
	/Makeshift\sMauler/,
	/Malicious\sIntent/,
	/Malignus/,
	/Mana\sBloom/,
	/Manor\sGargoyle/,
	/Manor\sSkeleton/,
	/Mark\sof Mutiny/,
	/Mark\sof the Vampire/,
	/Markov\sBlademaster/,
	/Markov\sPatrician/,
	/Markov\sWarlord/,
	/Marrow\sBats/,
	/Martial\sLaw/,
	/Mask\sof Avacyn/,
	/Mass\sAppeal/,
	/Master\sof the Pearl Trident/,
	/Mausoleum\sGuard/,
	/Maw\sof the Mire/,
	/Memory's\sJourney/,
	/Mental\sAgony/,
	/Mentor\sof the Meek/,
	/Reckless\sWaif/,
	/Merciless\sPredator/,
	/Mercurial\sChemister/,
	/Merfolk\sof the Pearl Trident/,
	/Midnight\sDuelist/,
	/Midnight\sGuard/,
	/Midnight\sHaunting/,
	/Midvast\sProtector/,
	/Mikaeus,\sthe Lunarch/,
	/Mikaeus,\sthe Unhallowed/,
	/Mind\sRot/,
	/Mind\sSculpt/,
	/Mindclaw\sShaman/,
	/Mindshrieker/,
	/Minotaur\sAggressor/,
	/Mirror-Mad\sPhantasm/,
	/Mist\sRaven/,
	/Misthollow\sGriffin/,
	/Mizzium\sMortars/,
	/Mizzium\sSkin/,
	/Moan\sof the Unhallowed/,
	/Mogg\sFlunkies/,
	/Moldgraf\sMonstrosity/,
	/Moment\sof Heroism/,
	/Mondronen\sShaman/,
	/Tovolar's\sMagehunter/,
	/Moon\sHeron/,
	/Moonlight\sGeist/,
	/Moonmist/,
	/Scorned\sVillager/,
	/Moonscarred\sWerewolf/,
	/Moonsilver\sSpear/,
	/Moonveil\sDragon/,
	/Moorland\sHaunt/,
	/Moorland\sInquisitor/,
	/Morkrut\sBanshee/,
	/Mountain/,
	/Mulch/,
	/Murder/,
	/Murder\sof Crows/,
	/Mutilate/,
	/Mwonvuli\sBeast Tracker/,
	/Mystic\sRetrieval/,
	/Narstad\sScrapper/,
	/Natural\sEnd/,
	/Naturalize/,
	/Nearheath\sPilgrim/,
	/Nearheath\sStalker/,
	/Necrobite/,
	/Necropolis\sRegent/,
	/Nefarox,\sOverlord of Grixis/,
	/Negate/,
	/Nephalia\sDrownyard/,
	/Nephalia\sSeakite/,
	/Nephalia\sSmuggler/,
	/Nettle\sSwine/,
	/Nevermore/,
	/New\sPrahv Guildmage/,
	/Niblis\sof the Breath/,
	/Niblis\sof the Mist/,
	/Niblis\sof the Urn/,
	/Nicol\sBolas, Planeswalker/,
	/Night\sRevelers/,
	/Night\sTerrors/,
	/Nightbird's\sClutches/,
	/Nightshade\sPeddler/,
	/Niv-Mizzet,\sDracogenius/,
	/Nivix\sGuildmage/,
	/Nivmagus\sElemental/,
	/Oak\sStreet Innkeeper/,
	/Oblivion\sRing/,
	/Odric,\sMaster Tactician/,
	/Ogre\sJailbreaker/,
	/Olivia\sVoldaren/,
	/Omniscience/,
	/One-Eyed\sScarecrow/,
	/Orchard\sSpirit/,
	/Otherworld\sAtlas/,
	/Outwit/,
	/Overgrown\sTomb/,
	/Pacifism/,
	/Pack\sRat/,
	/Palisade\sGiant/,
	/Parallel\sLives/,
	/Paralyzing\sGrasp/,
	/Paraselene/,
	/Past\sin Flames/,
	/Pathbreaker\sWurm/,
	/Peel\sfrom Reality/,
	/Perilous\sShadow/,
	/Phantom\sGeneral/,
	/Phylactery\sLich/,
	/Phyrexian\sHulk/,
	/Pillar\sof Flame/,
	/Pillarfield\sOx/,
	/Pitchburn\sDevils/,
	/Pithing\sNeedle/,
	/Plains/,
	/Planar\sCleansing/,
	/Plummet/,
	/Polluted\sDead/,
	/Precinct\sCaptain/,
	/Predator\sOoze/,
	/Predator's\sGambit/,
	/Predatory\sRampage/,
	/Prey\sUpon/,
	/Primal\sClay/,
	/Primal\sHuntbeast/,
	/Primal\sSurge/,
	/Primordial\sHydra/,
	/Prized\sElephant/,
	/Psychic\sSpiral/,
	/Public\sExecution/,
	/Purify\sthe Grave/,
	/Pursuit\sof Flight/,
	/Pyreheart\sWolf/,
	/Pyroconvergence/,
	/Quirion\sDryad/,
	/Racecourse\sFury/,
	/Rage\sThrower/,
	/Raging\sPoltergeist/,
	/Rain\sof Blades/,
	/Rain\sof Thorns/,
	/Rakdos\sCackler/,
	/Rakdos\sCharm/,
	/Rakdos\sGuildgate/,
	/Rakdos\sKeyrune/,
	/Rakdos\sRagemutt/,
	/Rakdos\sRingleader/,
	/Rakdos\sShred-Freak/,
	/Rakdos's\sReturn/,
	/Rakdos,\sLord of Riots/,
	/Rakish\sHeir/,
	/Rally\sthe Peasants/,
	/Tormented\sPariah/,
	/Rampaging\sWerewolf/,
	/Rancor/,
	/Ranger's\sGuile/,
	/Ranger's\sPath/,
	/Ravenous\sRats/,
	/Ray\sof Revelation/,
	/Reap\sthe Seagraf/,
	/Reaper\sfrom the Abyss/,
	/Rebuke/,
	/Reckless\sBrute/,
	/Redirect/,
	/Reforge\sthe Soul/,
	/Relentless\sSkaabs/,
	/Reliquary\sTower/,
	/Renegade\sDemon/,
	/Requiem\sAngel/,
	/Rest\sin Peace/,
	/Restoration\sAngel/,
	/Revenge\sof the Hunted/,
	/Reverberate/,
	/Revive/,
	/Rewind/,
	/Rhox\sFaithmender/,
	/Riders\sof Gavony/,
	/Righteous\sAuthority/,
	/Righteous\sBlow/,
	/Ring\sof Evos Isle/,
	/Ring\sof Kalonia/,
	/Ring\sof Thune/,
	/Ring\sof Valkas/,
	/Ring\sof Xathrid/,
	/Riot\sDevils/,
	/Riot\sRingleader/,
	/Rise\sfrom the Grave/,
	/Risen\sSanctuary/,
	/Rite\sof Ruin/,
	/Rites\sof Reaping/,
	/Rix\sMaadi Guildmage/,
	/Roaring\sPrimadox/,
	/Rogue's\sPassage/,
	/Rolling\sTemblor/,
	/Rooftop\sStorm/,
	/Rootborn\sDefenses/,
	/Rootbound\sCrag/,
	/Rotcrown\sGhoul/,
	/Rotting\sFensnake/,
	/Rubbleback\sRhino/,
	/Rummaging\sGoblin/,
	/Runechanter's\sPike/,
	/Runewing/,
	/Runic\sRepetition/,
	/Rush\sof Blood/,
	/Russet\sWolves/,
	/Safe\sPassage/,
	/Sanctuary\sCat/,
	/Sands\sof Delirium/,
	/Savage\sSurge/,
	/Saving\sGrasp/,
	/Scalding\sDevil/,
	/Scorch\sthe Fields/,
	/Scourge\sof Geier Reach/,
	/Scrapskin\sDrake/,
	/Screeching\sBat/,
	/Stalking\sVampire/,
	/Screeching\sSkaab/,
	/Scroll\sof Avacyn/,
	/Scroll\sof Griselbrand/,
	/Scroll\sThief/,
	/Seance/,
	/Search\sthe City/,
	/Search\sWarrant/,
	/Searchlight\sGeist/,
	/Searing\sSpear/,
	/Second\sGuess/,
	/Secrets\sof the Dead/,
	/Security\sBlockade/,
	/Seek\sthe Horizon/,
	/Selesnya\sCharm/,
	/Selesnya\sGuildgate/,
	/Selesnya\sKeyrune/,
	/Selesnya\sSentry/,
	/Selfless\sCathar/,
	/Selhoff\sOccultist/,
	/Seller\sof Songbirds/,
	/Sensory\sDeprivation/,
	/Sentinel\sSpider/,
	/Seraph\sof Dawn/,
	/Seraph\sSanctuary/,
	/Serpent's\sGift/,
	/Serra\sAngel/,
	/Serra\sAvatar/,
	/Serra\sAvenger/,
	/Servant\sof Nefarox/,
	/Sever\sthe Bloodline/,
	/Sewer\sShambler/,
	/Sharpened\sPitchfork/,
	/Shattered\sPerception/,
	/Sheltering\sWord/,
	/Shimian\sSpecter/,
	/Shimmering\sGrotto/,
	/Show\sof Valor/,
	/Shriekgeist/,
	/Shrieking\sAffliction/,
	/Sigarda,\sHost of Herons/,
	/Sightless\sGhoul/,
	/Sign\sin Blood/,
	/Silent\sDeparture/,
	/Silklash\sSpider/,
	/Silver-Inlaid\sDagger/,
	/Silverblade\sPaladin/,
	/Silverchase\sFox/,
	/Silverclaw\sGriffin/,
	/Silvercoat\sLion/,
	/Skaab\sGoliath/,
	/Skaab\sRuinator/,
	/Skeletal\sGrimace/,
	/Skillful\sLunge/,
	/Skirsdag\sCultist/,
	/Skirsdag\sFlayer/,
	/Skirsdag\sHigh Priest/,
	/Skull\sRend/,
	/Skyline\sPredator/,
	/Skymark\sRoc/,
	/Slaughter\sGames/,
	/Slayer\sof the Wicked/,
	/Slayers'\sStronghold/,
	/Sleep/,
	/Slime\sMolding/,
	/Slitherhead/,
	/Sluiceway\sScorpion/,
	/Slum\sReaper/,
	/Slumbering\sDragon/,
	/Smelt/,
	/Smite\sthe Monstrous/,
	/Snapcaster\sMage/,
	/Snare\sthe Skies/,
	/Somberwald\sDryad/,
	/Somberwald\sSage/,
	/Somberwald\sSpider/,
	/Somberwald\sVigilante/,
	/Sorin,\sLord of Innistrad/,
	/Soul\sof the Harvest/,
	/Soul\sTithe/,
	/Soulcage\sFiend/,
	/Soulsworn\sSpirit/,
	/Spare\sfrom Evil/,
	/Spawn\sof Rix Maadi/,
	/Spectral\sFlight/,
	/Spectral\sGateguards/,
	/Spectral\sPrison/,
	/Spectral\sRider/,
	/Spelltwine/,
	/Sphere\sof Safety/,
	/Sphinx\sof the Chimes/,
	/Sphinx\sof Uthuun/,
	/Sphinx's\sRevelation/,
	/Spider\sSpawning/,
	/Spidery\sGrasp/,
	/Spiked\sBaloth/,
	/Spirit\sAway/,
	/Spiteful\sShadows/,
	/Splatter\sThug/,
	/Splinterfright/,
	/Stab\sWound/,
	/Staff\sof Nin/,
	/Stealer\sof Secrets/,
	/Steam\sVents/,
	/Stensia\sBloodhall/,
	/Stern\sMentor/,
	/Stitched\sDrake/,
	/Stitcher's\sApprentice/,
	/Stolen\sGoods/,
	/Stonefare\sCrocodile/,
	/Stonewright/,
	/Stony\sSilence/,
	/Stormbound\sGeist/,
	/Stormtide\sLeviathan/,
	/Strangleroot\sGeist/,
	/Street\sSpasm/,
	/Street\sSweeper/,
	/Stromkirk\sCaptain/,
	/Stromkirk\sNoble/,
	/Stromkirk\sPatrol/,
	/Stuffy\sDoll/,
	/Sturmgeist/,
	/Sublime\sArchangel/,
	/Sudden\sDisappearance/,
	/Sulfur\sFalls/,
	/Sundering\sGrowth/,
	/Sunpetal\sGrove/,
	/Sunspire\sGriffin/,
	/Supreme\sVerdict/,
	/Survey\sthe Wreckage/,
	/Swamp/,
	/Swift\sJustice/,
	/Switcheroo/,
	/Syncopate/,
	/Tablet\sof the Guilds/,
	/Talons\sof Falkenrath/,
	/Talrand's\sInvocation/,
	/Talrand,\sSky Summoner/,
	/Tamiyo,\sthe Moon Sage/,
	/Tandem\sLookout/,
	/Tavern\sSwindler/,
	/Teleportal/,
	/Temple\sGarden/,
	/Temporal\sMastery/,
	/Tenement\sCrasher/,
	/Terminus/,
	/Terrifying\sPresence/,
	/Terrus\sWurm/,
	/Thalia,\sGuardian of Thraben/,
	/Thatcher\sRevolt/,
	/Think\sTwice/,
	/Thought\sScour/,
	/Thoughtflare/,
	/Thraben\sDoomsayer/,
	/Thraben\sHeretic/,
	/Thraben\sSentry/,
	/Thraben\sMilitia/,
	/Thraben\sPurebloods/,
	/Thraben\sValiant/,
	/Thragtusk/,
	/Thrill-Kill\sAssassin/,
	/Thunderbolt/,
	/Thundermaw\sHellkite/,
	/Thunderous\sWrath/,
	/Tibalt,\sthe Fiend-Blooded/,
	/Timberland\sGuide/,
	/Timberpack\sWolf/,
	/Titanic\sGrowth/,
	/Torch\sFiend/,
	/Tormented\sSoul/,
	/Tormentor's\sTrident/,
	/Tormod's\sCrypt/,
	/Touch\sof the Eternal/,
	/Tower\sDrake/,
	/Tower\sGeist/,
	/Towering\sIndrik/,
	/Tracker's\sInstincts/,
	/Trading\sPost/,
	/Tragic\sSlip/,
	/Trained\sCaracal/,
	/Traitorous\sBlood/,
	/Traitorous\sInstinct/,
	/Transguild\sPromenade/,
	/Travel\sPreparations/,
	/Traveler's\sAmulet/,
	/Treacherous\sPit-Dweller/,
	/Treasured\sFind/,
	/Tree\sof Redemption/,
	/Trepanation\sBlade/,
	/Trestle\sTroll/,
	/Tribute\sto Hunger/,
	/Tricks\sof the Trade/,
	/Triumph\sof Cruelty/,
	/Triumph\sof Ferocity/,
	/Trostani's\sJudgment/,
	/Trostani,\sSelesnya's Voice/,
	/Trumpet\sBlast/,
	/Trusted\sForcemage/,
	/Turn\sto Slag/,
	/Typhoid\sRats/,
	/Tyrant\sof Discord/,
	/Ultimate\sPrice/,
	/Ulvenwald\sBear/,
	/Ulvenwald\sMystics/,
	/Ulvenwald\sPrimordials/,
	/Ulvenwald\sTracker/,
	/Unbreathing\sHorde/,
	/Unburial\sRites/,
	/Uncanny\sSpeed/,
	/Undead\sAlchemist/,
	/Undead\sExecutioner/,
	/Underworld\sConnections/,
	/Undying\sEvil/,
	/Unhallowed\sPact/,
	/Unruly\sMob/,
	/Unsummon/,
	/Urban\sBurgeoning/,
	/Urgent\sExorcism/,
	/Utvara\sHellkite/,
	/Vampire\sInterloper/,
	/Vampire\sNighthawk/,
	/Vampire\sNocturnus/,
	/Vampiric\sFury/,
	/Vandalblast/,
	/Vanguard's\sShield/,
	/Vanishment/,
	/Vassal\sSoul/,
	/Vastwood\sGorger/,
	/Vault\sof the Archangel/,
	/Vedalken\sEntrancer/,
	/Veilborn\sGhoul/,
	/Vengeful\sVampire/,
	/Vessel\sof Endless Rest/,
	/Vexing\sDevil/,
	/Viashino\sRacketeer/,
	/Victim\sof Night/,
	/Vigilante\sJustice/,
	/Vile\sRebirth/,
	/Village\sBell-Ringer/,
	/Village\sCannibals/,
	/Village\sSurvivors/,
	/Vitu-Ghazi\sGuildmage/,
	/Voice\sof the Provinces/,
	/Voiceless\sSpirit/,
	/Void\sStalker/,
	/Voidwielder/,
	/Volatile\sRig/,
	/Volcanic\sGeyser/,
	/Volcanic\sStrength/,
	/Vorapede/,
	/Vorstclaw/,
	/Vraska\sthe Unseen/,
	/Wakedancer/,
	/Walking\sCorpse/,
	/Wall\sof Fire/,
	/Wandering\sWolf/,
	/War\sFalcon/,
	/War\sPriest of Thune/,
	/Warclamp\sMastiff/,
	/Warden\sof the Wall/,
	/Watercourser/,
	/Wayfaring\sTemple/,
	/Welkin\sTern/,
	/Afflicted\sDeserter/,
	/Werewolf\sRansacker/,
	/Wild\sBeastmaster/,
	/Wild\sDefiance/,
	/Wild\sGuess/,
	/Wild\sHunger/,
	/Wildwood\sGeist/,
	/Wind\sDrake/,
	/Wingcrafter/,
	/Wit's\sEnd/,
	/Witchbane\sOrb/,
	/Wolfhunter's\sQuiver/,
	/Wolfir\sAvenger/,
	/Wolfir\sSilverheart/,
	/Wooden\sStake/,
	/Woodland\sCemetery/,
	/Woodland\sSleuth/,
	/Worldfire/,
	/Worldspine\sWurm/,
	/Wrack\swith Madness/,
	/Wreath\sof Geists/,
	/Xathrid\sGorgon/,
	/Yeva's\sForcemage/,
	/Yeva,\sNature's Herald/,
	/Yew\sSpirit/,
	/Young\sWolf/,
	/Zanikev\sLocust/,
	/Zealous\sConscripts/,
	/Zealous\sStrike/,
	/Zombie\sApocalypse/,
	/Zombie\sGoliath/
];
